---
title: "R Notebook"
output: html_notebook
---

```{r}
library(broom)
library(tidyverse)
library(car)
library(ggpubr)
library(lmtest)
library(DescTools)
library(patchwork)
library(corrplot)
library(mycor)
library(factoextra)

FilePath = "~/Dropbox/PhD/MAR20 WIP - Stat Modelling/Final Output/"
`%notin%` = Negate(`%in%`)
calc_loocv_rmse = function(model) { sqrt(mean((resid(model) / (1 - hatvalues(model))) ^
2)) }

#Data for temporal signalling (Fig 1)
ConstSig = read.csv("~/Dropbox/PhD/MAR20 WIP - Stat Modelling/2021 Analysis/Constituitive Signalling.csv")
ConstSig$Protein = gsub("pFgfr", "p-Fgfr", ConstSig$Protein)

#Data for signalling pathway cross talk (Fig 1)
CrossTalkDataNormToES = read.csv("~/Dropbox/PhD/MAR20 WIP - Stat Modelling/2021 Analysis/CrossTalkData_NormToES_Long.csv")

#Control data for Morphology (Fig 2)
Morph_Controls = read.csv("~/Dropbox/PhD/MAR20 WIP - Stat Modelling/2021 Analysis/Morph_Controls.csv")

#Data for models (Figs 2, 3, 4, S3, S4, S5, S7, S8, S9, S10)
AllVariables = read.csv("~/Dropbox/PhD/MAR20 WIP - Stat Modelling/2021 Analysis/StatModelPaper_AllData.csv")
AllVariables$Combo = paste(ifelse(AllVariables$U == 1,  "U", ""), ifelse(AllVariables$S == 1,  "S", ""),ifelse(AllVariables$L == 1,  "L", ""),ifelse(AllVariables$R == 1,  "R", ""),ifelse(AllVariables$P == 1,  "P", ""), sep="")
AllVariables$Combo = sapply(strsplit(AllVariables$Combo, ""), paste, collapse="+")
AllVariables$Combo <- sub("^$", "DMSO", AllVariables$Combo)
colnames(AllVariables)[1] = "Name"
colnames(AllVariables) = gsub("\\.", "", colnames(AllVariables))

#BRANN model outputs computed by Dave Winkler  (Figs 2, 3, 4, S3, S4, S5, S7, S8, S9, S10)
BRANN_AvP = read.csv("~/Dropbox/PhD/MAR20 WIP - Stat Modelling/All_BRANN_Results_FEB22.csv")

#Control data for emergent properties (Figs 3, S4)
EPLControlData = read.csv("~/Dropbox/PhD/MAR20 WIP - Stat Modelling/EPL Control Data - All Assays.csv")
EPLControlData$Exp = gsub("Cell Growth", "CellNoNorm",  EPLControlData$Exp)

#Control data for qPCR (Figs 4, S5)
EPLControlData_PCR = read.csv("~/Dropbox/PhD/MAR20 WIP - Stat Modelling/2021 Analysis/EPL and Cont PCR - All Days.csv")
EPLControlData_PCR = na.omit(EPLControlData_PCR)

#Data for functional assay (Fig S6)
FunctionalAssay = read.csv("~/Dropbox/PhD/MAR20 WIP - Stat Modelling/2021 Analysis/FunctionalAssay_Data.csv")
FunctionalAssay$X = NULL
FunctionalAssay = na.omit(FunctionalAssay)


#Colours for plots
ColourLinear = "#e07a5f" #Red
ColourTwoWay = "#3d405b" #Blue
ColourFiveWay = "#81b29a" #Green
ColourBRANN = "#f2cc8f" #Yellow
ColourHeatmapLow = "#81b29a" #Green
ColourHeatmapHigh = "#3D405b" #Blue
ColourHeatmapMid = "#FFFFFF" #White
ColourNeutral = "#e5e6e3" #Light Grey
```

### FIGURE 1: Control Data
```{r}
########## 1B: MORPHOLOGY ##########
Morph_Controls$Condition = factor(Morph_Controls$Condition, levels = c("1000 U/mL LIF", "330 U/mL LIF", "330 U/mL LIF + Pro", "0 U/mL LIF"))
ANOVAResTable = as.data.frame(DunnettTest(x=Morph_Controls$Value, g=Morph_Controls$Condition)[[1]])
row.names(ANOVAResTable) = gsub("-1000 U/mL LIF", "", row.names(ANOVAResTable))
ANOVAResTable$Sig <- ifelse(ANOVAResTable$pval <0.05,  "*", NA)


GoIControls_Summarised = Morph_Controls %>% group_by(Condition) %>% summarise(n = n(), Mean = mean(Value), stdev = sd(Value), se=sd(Value)/sqrt(n())) 
GoIControls_Summarised$Condition = factor(GoIControls_Summarised$Condition, levels = c("1000 U/mL LIF", "330 U/mL LIF", "330 U/mL LIF + Pro", "0 U/mL LIF"))

MorphwStats = merge(GoIControls_Summarised, ANOVAResTable,  by.x = "Condition", by.y = 0, all=T)
MorphwStats$ConditionWn = paste(MorphwStats$Condition, "\n n=", MorphwStats$n, sep="")
MorphwStats$ConditionWn = gsub("mL", "\nmL", gsub("LIF", "LIF\n", MorphwStats$ConditionWn))
Morph_Controls_merge = merge(MorphwStats, Morph_Controls, by = "Condition")
MorphwStats <- MorphwStats[order(MorphwStats$Condition),] 
MorphwStats$ConditionWn = factor(MorphwStats$ConditionWn, levels = MorphwStats$ConditionWn)

ControlFig = list()
ControlFig[[paste("Morphology", "_i_Control", sep="")]] = ggplot(MorphwStats, aes(x=ConditionWn, y=Mean)) + geom_col(fill = ColourNeutral, color = "#000000", position = position_dodge(width = 0.9), width = 0.9)+ ggtitle("") + theme_classic() + ylab("Morphology Score") + xlab("")+ geom_point( aes(colour = ColourTwoWay, shape = Sig, y = Mean + sign(Mean) * (se + (se*6))), position = position_dodge(width = 0.9), size = 1, show.legend = F) + geom_errorbar(aes(ymin = Mean-se, ymax = Mean+se), position = position_dodge(width = 0.9), width = 0.2) + scale_shape_manual(values=c(8))   + theme(plot.title = element_text(face = "bold"), axis.text.x = element_text(face = "bold", size =8), axis.text.y = element_text(size =8), axis.title.y = element_text(size=8)) + scale_y_continuous(limits = c(0,2.2), expand = c(0,0))+ geom_point(data=Morph_Controls_merge, aes(x = ConditionWn, y =Value), size=0.5)

pdf(paste(FilePath, "Figure1B_MorphControls.pdf", sep=""), height = 2.5, width = 4)
print(ControlFig)
dev.off()


########## 1C-E: EMERGENT PROPERTIES ##########
for(GoI in c("CellNoNorm", "Apoptosis", "Prolif")){ 
if(GoI == "Apoptosis"){
PlotTitle = "Apoptosis"
Control_Ylab = "% Annexin V+"
errormargin = 2.5
}
if(GoI == "Prolif"){
PlotTitle = "Proliferation"
Control_Ylab = "% BrdU +"
errormargin = 3

}
if(GoI == "CellNoNorm"){
PlotTitle = "Cell Number"
Control_Ylab = "Fold change"
errormargin = 2.8
}
GoIControls = subset(EPLControlData, EPLControlData$Exp %in% GoI)
GetMaxHeight = max(GoIControls$Value)*1.2
GEXPanel_Controls = list()

CompileData = as.data.frame(matrix(ncol =13, nrow=0))
colnames(CompileData) = c("Condition", "Day", "n", "Mean", "stdev", "se", "diff", "lwr.ci", "upr.ci", "pval", "Sig", "ConditionWn", "MaxHeight")

CompileData2 = as.data.frame(matrix(ncol =16, nrow=0))
colnames(CompileData2) = c("Condition", "Day.x", "n", "Mean", "stdev", "se", "diff", "lwr.ci", "upr.ci", "pval", "Sig", "ConditionWn", "Exp", "Day.y", "Value", "Day")

for(Dayz in c(2,4,6)){
EPLControlData_Subs = subset(GoIControls, GoIControls$Day %in% Dayz)
Control_GraphInputs = EPLControlData_Subs %>% group_by(Condition, Day) %>% summarise(n = n(), Mean = mean(Value), stdev = sd(Value), se=sd(Value)/sqrt(n()))

EPLControlData_Subs$Condition = factor(EPLControlData_Subs$Condition, levels = c("1000 U/mL LIF", "330 U/mL LIF", "330 U/mL LIF + Pro", "0 U/mL LIF"))
ANOVAResTable = as.data.frame(DunnettTest(x=EPLControlData_Subs$Value, g=EPLControlData_Subs$Condition)[[1]])
row.names(ANOVAResTable) = gsub("-1000 U/mL LIF", "", row.names(ANOVAResTable))
ANOVAResTable$Sig <- ifelse(ANOVAResTable$pval <0.05,  "*", NA)
SummedwStats = merge(Control_GraphInputs, ANOVAResTable,  by.x = "Condition", by.y = 0, all=T)

SummedwStats$ConditionWn = paste("D", SummedwStats$Day, "\n n=", SummedwStats$n,  sep="")
SummedwStats$ConditionWn = gsub("mL", "\nmL", gsub("LIF", "LIF\n", SummedwStats$ConditionWn))
EPLControlData_Subs_merge = merge(SummedwStats, EPLControlData_Subs, by = "Condition")

SummedwStats$Day = paste("Day", SummedwStats$Day)
SummedwStats$MaxHeight = (SummedwStats$Mean +  SummedwStats$se)
SummedwStats$Condition = factor(SummedwStats$Condition, levels = c("1000 U/mL LIF", "330 U/mL LIF", "330 U/mL LIF + Pro", "0 U/mL LIF"))
SummedwStats <- SummedwStats[order(SummedwStats$Condition),] 
CompileData = rbind(CompileData, SummedwStats)

EPLControlData_Subs_merge$Day = paste("Day", EPLControlData_Subs_merge$Day.x)
CompileData2 = rbind(CompileData2, EPLControlData_Subs_merge)

}

for(x in unique(CompileData$Condition)){
Subs = subset(CompileData, CompileData$Condition %in% x)
Subs$ConditionWn = factor(Subs$ConditionWn)
Subs2 = subset(CompileData2, CompileData2$Condition %in% x)
Subs2$ConditionWn = factor(Subs2$ConditionWn)
  
GEXPanel_Controls[[x]] = ggplot(Subs, aes(x=ConditionWn, y=Mean)) + geom_col(fill = ColourNeutral, color = "#000000", position = position_dodge(width = 0.9), width = 0.9)  +theme_classic()  + xlab("")+ geom_point(aes(colour = ColourTwoWay,  shape = Sig, y = Mean + sign(Mean) * (se + (se*errormargin))), position = position_dodge(width = 0.9), size = 1, show.legend = F) + geom_errorbar(aes(ymin = Mean-se, ymax = Mean+se), position = position_dodge(width = 0.9), width = 0.2) + scale_shape_manual(values=c(8)) + theme(plot.title = element_text(face = "bold", size = 15), strip.background = element_blank(), strip.text.x = element_text(face = "bold", size = 12), axis.title = element_text(size=8), axis.text.y = element_text(size=8), axis.text.x = element_text(size=8, face = "bold"))  + scale_y_continuous(limits = c(0, GetMaxHeight), expand = c(0,0))  + scale_x_discrete(labels = Subs$ConditionWn) + geom_point(data=Subs2, aes(x = ConditionWn, y =Value), size=0.3) 
}

GEXPanel_Controls[[1]] = GEXPanel_Controls[[1]] + ylab(Control_Ylab) + ggtitle("", subtitle = "1000 U/mL \nLIF") + theme(plot.subtitle = element_text(size = 8, face="italic"), axis.title = element_text(size = 8), axis.text.x = element_text(size = 8, face = "bold"), axis.text.y = element_text(size = 8))
GEXPanel_Controls[[2]] = GEXPanel_Controls[[2]] + ggtitle("", subtitle = "330 U/mL LIF") + theme(axis.text.y = element_blank(), axis.line.y = element_blank(), axis.ticks.y = element_blank(), axis.title.y = element_blank()) + theme(plot.subtitle = element_text(size = 8, face="italic"), axis.text = element_text(size = 8, face = "bold"))
GEXPanel_Controls[[3]] = GEXPanel_Controls[[3]] + ggtitle("", subtitle = "330 U/mL LIF  \n+ Pro")  + theme(axis.text.y = element_blank(), axis.line.y = element_blank(), axis.ticks.y = element_blank(), axis.title.y = element_blank())+ theme(plot.subtitle = element_text(size = 8, face="italic"), axis.text = element_text(size = 8, face = "bold"))
GEXPanel_Controls[[4]] = GEXPanel_Controls[[4]] + ggtitle("", subtitle = "0 U/mL LIF" )  + theme(axis.text.y = element_blank(), axis.line.y = element_blank(), axis.ticks.y = element_blank(), axis.title.y = element_blank())+ theme(plot.subtitle = element_text( size = 8, face="italic"), axis.text = element_text(size = 8, face = "bold"))

ControlFig[[paste(GoI, "_i_Control", sep="")]] = ggarrange(plotlist =  GEXPanel_Controls, nrow=1, widths = c(1.3,1,1,1))
}

pdf(paste(FilePath, "Figure1CDE_Control_EmergProp.pdf", sep=""), width = 4, height = 3)
print(ControlFig)
dev.off()



########## 1F: GENE EXPRESSION ##########

Data_To_Plot = c("Rex1", "Oct4", "Dnmt3b", "Fgf5",  "Lefty2", "Otx2", "Mixl1")
CompileGEX = as.data.frame(matrix(ncol=13, nrow=0))
colnames(CompileGEX) = c("Day", "Condition","Gene", "n", "Mean", "stdev", "se", "diff", "lwr.ci", "upr.ci", "pval", "Sig", "DayWn")
ControlFig = list()
for(GoI in Data_To_Plot){
if("Lefty2" %in% Data_To_Plot){errormargin = 0.8}else{errormargin =1}
GoIControls = subset(EPLControlData_PCR, EPLControlData_PCR$Gene %in% GoI)
GetMaxHeight = max(GoIControls$Value)*1.3
GetMinHeight = min(GoIControls$Value)*1.4
GEXPanel_Controls = list()

for(Condit in c( "330 U/mL LIF", "330 U/mL LIF + Pro", "0 U/mL LIF")){
EPLControlData_Subs = subset(GoIControls, GoIControls$Condition %in% Condit)
ControlPCR_GraphInputs = EPLControlData_Subs %>% group_by(Condition, Day, Gene) %>% summarise(n = n(), Mean = mean(Value), stdev = sd(Value), se=sd(Value)/sqrt(n())) 

ControlGroup = as.data.frame(matrix(ncol = 0, nrow = max(as.data.frame(table(EPLControlData_Subs$Day))$Freq)))  
ControlGroup$Condition = Condit
ControlGroup$Gene = GoI
ControlGroup$Day = "Day 0"
ControlGroup$Value = 0

DataForANOVA = rbind(EPLControlData_Subs, ControlGroup)
DataForANOVA$Day = factor(DataForANOVA$Day, levels = c("Day 0", "Day 2", "Day 4", "Day 6"))
ANOVAResTable = as.data.frame(DunnettTest(x=DataForANOVA$Value, g=DataForANOVA$Day)[[1]])
row.names(ANOVAResTable) = gsub("-Day 0", "", row.names(ANOVAResTable))
ControlPCR_GraphInputsWPval = merge(ControlPCR_GraphInputs, ANOVAResTable, by.x = "Day", by.y = 0, all = T)
ControlPCR_GraphInputsWPval$Sig <- ifelse(ControlPCR_GraphInputsWPval$pval <0.05,  "*", NA)
ControlPCR_GraphInputsWPval$Day = gsub("Day ", "D", ControlPCR_GraphInputsWPval$Day)
ControlPCR_GraphInputsWPval$Day = factor(ControlPCR_GraphInputsWPval$Day, levels = c("D2", "D4", "D6"))
ControlPCR_GraphInputsWPval$DayWn = paste(ControlPCR_GraphInputsWPval$Day, "\n n=", ControlPCR_GraphInputsWPval$n, sep="")
EPLControlData_Subs$Day = gsub("Day ", "D", EPLControlData_Subs$Day)
EPLControlData_Subs$Day = factor(EPLControlData_Subs$Day, levels = c("D2", "D4", "D6"))
CompileGEX = rbind(CompileGEX, ControlPCR_GraphInputsWPval)
}}

CompileQPCR_Main = list()
for(x in c("330 U/mL LIF", "330 U/mL LIF + Pro", "0 U/mL LIF")){
CompileQPCR = list()
SubA = subset(CompileGEX, CompileGEX$Condition %in% x)
SubB = subset(EPLControlData_PCR, EPLControlData_PCR$Condition %in% x & EPLControlData_PCR$Gene %in% Data_To_Plot)

for(y in c("Rex1", "Oct4", "Dnmt3b", "Fgf5",  "Lefty2", "Otx2", "Mixl1")){
SubC = subset(SubA, SubA$Gene %in% y)
SubD = subset(EPLControlData_PCR, EPLControlData_PCR$Gene %in% y & EPLControlData_PCR$Condition %in% x)
SubD$Day = gsub("Day ", "D", SubD$Day)
SubE = SubC %>% dplyr::select(Day, DayWn)
SubE = unique(SubE)
SubD = merge(SubD, SubE, by = "Day")
errormargin = 1
if(y == "Rex1"){
CompileQPCR[[paste(x, y)]] = ggplot(SubC, aes(x=DayWn, y=Mean))+ facet_wrap(~Gene, nrow = 1)+geom_col(fill = ColourNeutral, color = "#000000", position = position_dodge(width = 0.9), width = 0.9)  +theme_classic() + ylab(expression(Log[2]~Fold~Change)) + xlab("")+ geom_point( aes(color = ColourTwoWay, shape = Sig, y = Mean  + sign(Mean) * (stdev + errormargin)), position = position_dodge(width = 0.9), size = 1, show.legend = F) + geom_errorbar(aes(ymin = Mean-se, ymax = Mean+se), position = position_dodge(width = 0.9), width = 0.2) + scale_shape_manual(values=c(8)) + theme(strip.text = element_text( size = 8, face = "bold.italic"), strip.background = element_blank(), axis.title.y = element_text(face = "bold", size = 8), axis.text.x = element_text(face = "bold", size = 8), axis.text.y = element_text(size = 8), axis.title = element_text(face = "bold", size = 8)) +geom_hline(yintercept=0) + scale_y_continuous(limits = c(-7, 12), expand = c(0,0)) + scale_x_discrete(labels = SubC$DayWn) + geom_point(data=SubD, aes(x = DayWn, y =Value), size=0.3)  
}else{
 CompileQPCR[[paste(x, y)]] = ggplot(SubC, aes(x=DayWn, y=Mean))+ facet_wrap(~Gene, nrow = 1)+geom_col(fill = ColourNeutral, color = "#000000", position = position_dodge(width = 0.9), width = 0.9)  +theme_classic() + ylab(expression(Log[2]~Fold~Change)) + xlab("")+ geom_point( aes(color = ColourTwoWay, shape = Sig, y = Mean  + sign(Mean) * (stdev + errormargin)), position = position_dodge(width = 0.9), size = 1, show.legend = F) + geom_errorbar(aes(ymin = Mean-se, ymax = Mean+se), position = position_dodge(width = 0.9), width = 0.2) + scale_shape_manual(values=c(8)) + theme( strip.text = element_text( size = 8, face = "bold.italic"), axis.text = element_text(face = "bold", size = 8), strip.background = element_blank(), axis.line.y = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank(), axis.title.y = element_blank()) +geom_hline(yintercept=0) + scale_y_continuous(limits = c(-7, 12), expand = c(0,0)) + scale_x_discrete(labels = SubC$DayWn) + geom_point(data=SubD, aes(x = DayWn, y =Value), size=0.3)  
}
}
CompileQPCR_Main[[x]] = ggarrange(plotlist = CompileQPCR, nrow=1, ncol =7, widths = c(1.5,1,1,1,1,1,1))
}

pdf(paste(FilePath, "Figure1F_Control_PCR.pdf", sep=""), width = 8, height = 3)
print(CompileQPCR_Main)
dev.off()
```


### FIGURE 2: Cell Signalling
```{r}
########## 2B: TEMPORAL SIGNALLING ##########
Figure2Plots = list()

ConstSig2 = ConstSig

ConstSig2$Value = log2(ConstSig2$Value) 
ConstSig2$Time = factor(ConstSig2$Time, levels = c("0 h", "0.16 h", "0.5 h", "1 h", "2 h", "6 h", "12 h", "24 h", "48 h", "96 h", "144 h" ))
ConstSig2$Protein = factor(ConstSig2$Protein, levels = c("p-Stat3@Y705", "p-Stat3@S727", "p-Fgfr", "p-Erk1/2", "p-Akt", "p-S6k", "p-Rps6",     "p-4epb1"))


Constituative = list()
for(Proteinz in rev(c("p-4epb1", "p-Rps6", "p-S6k", "p-Akt", "p-Erk1/2", "p-Fgfr", "p-Stat3@S727", "p-Stat3@Y705"))){
SubsDataForANOVA = subset(ConstSig2, ConstSig2$Protein %in% Proteinz)
SubsDataForTable = SubsDataForANOVA %>% group_by(Time, Protein) %>% dplyr::summarise(Mean = mean(Value), stdev = sd(Value), se=sd(Value)/sqrt(n())) 

ANOVAResTable = as.data.frame(DunnettTest(x=SubsDataForANOVA$Value, g=SubsDataForANOVA$Time)[[1]])
row.names(ANOVAResTable) = gsub("-0 h", "", row.names(ANOVAResTable))

SubsDataForTableWPval = merge(SubsDataForTable, ANOVAResTable, by.x = "Time", by.y = 0, all = T)

SubsDataForTableWPval$Sig <- ifelse(SubsDataForTableWPval$pval <0.05,  "*", NA)

GetMin = min(SubsDataForANOVA$Value)*1.1
GetMax = max(SubsDataForANOVA$Value)*1.1
if("*" %in% SubsDataForTableWPval$Sig){GetMax = max(SubsDataForANOVA$Value)*1.3}

Constituative[[Proteinz]] = ggplot(SubsDataForTableWPval, aes(x=Time, y=Mean))+geom_col(fill = ColourNeutral, color = "#000000", position = position_dodge(width = 0.9), width = 0.9)+ ggtitle(Proteinz)  +theme_classic() + geom_point( aes(color = ColourTwoWay, shape = Sig, y = Mean  + sign(Mean) * (stdev*2.2)), position = position_dodge(width = 0.9), size = 1, show.legend = F) + geom_errorbar(aes(ymin = Mean-se, ymax = Mean+se), position = position_dodge(width = 0.9), width = 0.2) + scale_shape_manual(values=c(8)) + theme(axis.text = element_text(face = "bold", size = 8),  axis.text.y = element_text(face = "bold", size = 8), axis.title.y = element_blank(), plot.title = element_text(face = "bold", size = 10), axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title.x = element_blank()) +geom_hline(yintercept=0) + scale_y_continuous(expand = c(0,0))+ geom_point(data=SubsDataForANOVA, aes(x = Time, y =Value), size=0.3) +scale_y_continuous(limits = c(GetMin, GetMax))
}

OUT = ggarrange(plotlist = Constituative, ncol = 1)


pdf(paste(FilePath, "Figure2B_TemporalSignalling.pdf",sep=""), width = 4.5, height = 7)
print(OUT)
dev.off()


########## 2D: 2H INHIB SUPRESSION ##########
CrossTalkDataNormToES = read.csv("~/Dropbox/PhD/MAR20 WIP - Stat Modelling/2021 Analysis/CrossTalkData_NormToES_Long.csv")
Inhib2H = list()
for(p in c("pERK", "pRPS6")){
if(p == "pERK"){p2 = "p-Erk1/2"}else{p2 = "p-Rps6"}
Reduced_phospho_2h0h = subset(CrossTalkDataNormToES, CrossTalkDataNormToES$Protein %in% p & CrossTalkDataNormToES$Time %in% c("2", "0"))
Reduced_phospho_2h0h$CondTime = paste(Reduced_phospho_2h0h$Inhib1, Reduced_phospho_2h0h$Time, sep="_")
Reduced_phospho_2h0h$CondTime = factor(Reduced_phospho_2h0h$CondTime, levels = c("NA_0", "NA_2", "U_2","S_2", "L_2", "R_2", "P_2"))
Reduced_phospho_2h0h$Value = log2(Reduced_phospho_2h0h$Value) ##### ADD LOG


Reduced_phospho_2h0h_Summ = Reduced_phospho_2h0h %>% group_by(Protein, Inhib1, Inhib2, Inhib_Dash, Time, CondTime) %>% dplyr::summarise(n = n(), Mean = mean(Value), stdev = sd(Value), se=sd(Value)/sqrt(n())) 

Reduced_phospho_2h0h[c("Inhib1")][is.na(Reduced_phospho_2h0h[c("Inhib1")])] <- "-"


ANOVARes = as.data.frame(DunnettTest(x=Reduced_phospho_2h0h$Value, g=Reduced_phospho_2h0h$CondTime)[1])
row.names(ANOVARes) = gsub("-NA_0", "", row.names(ANOVARes))

Reduced_phospho_2h0h_Summ = merge(Reduced_phospho_2h0h_Summ, ANOVARes, by.x = "CondTime", by.y = 0)
Reduced_phospho_2h0h_Summ$Inhib1[is.na(Reduced_phospho_2h0h_Summ$Inhib1)] <- "-"
Reduced_phospho_2h0h_Summ$Sig <- ifelse(Reduced_phospho_2h0h_Summ$NA_0.pval <0.05,  "*", NA)
Reduced_phospho_2h0h_Summ$Inhib1 = factor(Reduced_phospho_2h0h_Summ$Inhib1, levels = c("-", "U", "S", "L", "R", "P"))

Reduced_phospho_2h0h_Summ$Inhib1Wn = paste(Reduced_phospho_2h0h_Summ$Inhib1, "\n n=", Reduced_phospho_2h0h_Summ$n,  sep="")
Reduced_phospho_2h0h_Summ_merge = merge(Reduced_phospho_2h0h_Summ, Reduced_phospho_2h0h, by = "Inhib1")
Reduced_phospho_2h0h_Summ <- Reduced_phospho_2h0h_Summ[order(Reduced_phospho_2h0h_Summ$Inhib1),] 
Reduced_phospho_2h0h_Summ$Inhib1Wn = factor(Reduced_phospho_2h0h_Summ$Inhib1Wn, levels = Reduced_phospho_2h0h_Summ$Inhib1Wn)

if(p == "pERK"){SigLab = 2.5}else{SigLab = 1}

Inhib2H[[paste("2h", p)]] = ggplot(Reduced_phospho_2h0h_Summ, aes(x=Inhib1Wn, y=Mean)) + geom_col(fill = ColourNeutral, color = "#000000", position = position_dodge(width = 0.9), width = 0.9)  +theme_classic() + geom_hline(yintercept=0)+ ylab(expression(Log[2]~fold~change)) + xlab("") + geom_errorbar(aes(ymin = Mean-se, ymax = Mean+se, ), position = position_dodge(width = 0.9), width = 0.2) + ggtitle(p2) + geom_point( aes(color = ColourTwoWay, shape = Sig, y = Mean + sign(Mean) * (se + (se+SigLab))), position = position_dodge(width = 0.9), size = 1, show.legend = F) + scale_shape_manual(values=c(8))+ theme( plot.title = element_text(face = "bold", size = 8, hjust = 0.5), axis.title = element_text(size = 8), axis.text.x = element_text(size = 8, face = "bold"), axis.text.y = element_text(size = 8))   + geom_point(data=Reduced_phospho_2h0h_Summ_merge, aes(x = Inhib1Wn, y =Value), size=0.5) + scale_y_continuous(limits = c(min(Reduced_phospho_2h0h_Summ_merge$Value)*1.2, max(Reduced_phospho_2h0h_Summ_merge$Value)*1.1))


pdf(paste(FilePath, "Figure2D_2HInhib.pdf", sep=""), width = 2, height = 2)
print(Inhib2H)
dev.off()
}


########## 2E: CROSS TALK ##########

CrossTalkDataNormToES = read.csv("~/Dropbox/PhD/MAR20 WIP - Stat Modelling/2021 Analysis/CrossTalkData_NormToES_Long.csv")

CrossTalkDataNormToES$Combo = paste(CrossTalkDataNormToES$Inhib1, CrossTalkDataNormToES$Inhib_Dash, sep=" ")
CrossTalkDataNormToES$Combo = gsub("NA", "-", CrossTalkDataNormToES$Combo)
CrossTalkDataNormToES$Combo = factor(CrossTalkDataNormToES$Combo, levels = c("- -", "U -", "U U", "S -", "S S", "L -", "L L", "R -", "R R", "P -", "P P", "U S", "U L", "U R", "U P", "R U", "R S", "R L", "R P"))
CrossTalkDataNormToES$Value = log2(CrossTalkDataNormToES$Value+0.01)
SubsDataForTable = CrossTalkDataNormToES %>% group_by(Protein, Time, Combo) %>% dplyr::summarise(Mean = mean(Value), stdev = sd(Value), se=sd(Value)/sqrt(n())) 
SubsDataForTable$Pval_toPro = NA

#CrossTalk_Recompile = as.data.frame(matrix(ncol=11, nrow=0))
#colnames(CrossTalk_Recompile) = c("Protein", "Inhib1", "Inhib2", "Inhib_Dash", "Time", "Combo", "Mean", "stdev", "se", "Pval_toPro", "Pval_toES")

for(Proteinz in c("pERK", "pRPS6")){
CrossTalkInput = subset(CrossTalkDataNormToES, CrossTalkDataNormToES$Protein == Proteinz)

for(Timez in c(4,6,8,10)){
for(Dataz in c("U -", "U U", "S -", "S S", "L -", "L L", "R -", "R R", "P -", "P P", "U S", "U L", "U R", "U P", "R U", "R S", "R L", "R P")){
#SubsDataForANOVA = subset(CrossTalkInput, CrossTalkInput$Combo %in% c(Dataz, "- -") & CrossTalkInput$Time %in% Timez)
SubsDataForANOVA = subset(CrossTalkInput, CrossTalkInput$Combo %in% c(Dataz, "- -") & CrossTalkInput$Time %in% Timez)
SubsDataForANOVA$Combo = gsub("-", "_", SubsDataForANOVA$Combo)

ANOVARes = as.data.frame(DunnettTest(x=SubsDataForANOVA$Value, g=SubsDataForANOVA$Combo, control = "_ _")[[1]])
ANOVARes$Condition = gsub("_", "-", gsub("-.*", "",  row.names(ANOVARes)))

SubsDataForTable$Pval_toPro = ifelse(SubsDataForTable$Protein == Proteinz & SubsDataForTable$Time == Timez & SubsDataForTable$Combo %in% ANOVARes$Condition, ANOVARes$pval, SubsDataForTable$Pval_toPro) 
}}}


SubsDataForTable$Combo = factor(SubsDataForTable$Combo, levels = c("- -", "U -", "U U", "S -", "S S", "L -", "L L", "R -", "R R", "P -", "P P", "U S", "U L", "U R", "U P", "R U", "R S", "R L", "R P"))
levels(SubsDataForTable$Combo) <- gsub(" ", "\n", levels(SubsDataForTable$Combo))
levels(CrossTalkDataNormToES$Combo) <- gsub(" ", "\n", levels(CrossTalkDataNormToES$Combo))
CrossTalkDataNormToES_ForPlot = subset(CrossTalkDataNormToES, ! CrossTalkDataNormToES$Time %in% c(0,2, "0", "2"))
SubsDataForTable_ForPlot = subset(SubsDataForTable, ! SubsDataForTable$Time %in% c(0,2,"0", "2"))

SubsDataForTable_ForPlot$Sig <- ifelse(SubsDataForTable_ForPlot$Pval_toPro <0.05,  "*", NA)

CrossTalk = ggplot(SubsDataForTable_ForPlot, aes(x=Combo, y=Mean))+ facet_wrap(~Time + Protein, ncol = 2)+geom_col(fill = ColourNeutral, color = "#000000", position = position_dodge(width = 0.9), width = 0.9)+ xlab("") + ylab(expression(Log[2]~Fold~Change)) +theme_classic() + geom_point( aes(color = ColourTwoWay, shape = Sig, y = Mean  + sign(Mean) * (stdev + errormargin)), position = position_dodge(width = 0.9), size = 1, show.legend = F) + geom_errorbar(aes(ymin = Mean-se, ymax = Mean+se), position = position_dodge(width = 0.9), width = 0.2) + scale_shape_manual(values=c(8)) + theme( axis.text.x = element_text(face = "bold", size = 8), axis.text.y = element_text(size = 8), strip.background = element_blank(), strip.text = element_blank()) +geom_hline(yintercept=0) + scale_y_continuous(limits = c(min(CrossTalkDataNormToES_ForPlot$Value*1.2), max(CrossTalkDataNormToES_ForPlot$Value*1.1)), expand = c(0,0))  + geom_point(data=CrossTalkDataNormToES_ForPlot, aes(x = Combo, y =Value), size=0.3) 


pdf(paste(FilePath, "Figure2D_Crosstalk.pdf", sep=""), width = 12, height = 6)
print(CrossTalk)
dev.off()
```


### FIGURE 3 + S8: Emergent Property Models
```{r}
########## 3B: MORPHOLOGY ##########
Data_To_Plot = c("Morphology_Log") 
GEXPanel = list()
NRows = length(Data_To_Plot)

for(GoI_X in Data_To_Plot){
GoI = gsub("_.*", "", GoI_X)

########## DATA PREP ##########
SingleMetric_AllData =  AllVariables[, c("Name", "Combo", "U", "S", "L", "R", "P", GoI)]
SingleMetric_AllData$Response = SingleMetric_AllData[[GoI]]
SingleMetric_AllData[[GoI]] = NULL
SingleMetric_AllData = na.omit(SingleMetric_AllData)

SingleMetric_AllData$Name = NULL
SingleMetric_AllData$Combo = paste("Day", SingleMetric_AllData$Day, "_", SingleMetric_AllData$Combo, sep="")
Reduced = SingleMetric_AllData %>% group_by(Combo) %>% summarise_all(funs(mean))

GetReps = as.data.frame(table(SingleMetric_AllData$Combo))
ThreePlusReps = subset(GetReps, GetReps$Freq >=3)
Reduced_ThreePlus = subset(Reduced, Reduced$Combo %in% ThreePlusReps$Var1)
##########


########## APPLY TRANSFORMATIONS IF REQUIRED ##########
if(GoI_X %notin% GoI){
#If log then  
if(grepl("Log", GoI_X, fixed = TRUE) == T){
if(min(Reduced_ThreePlus$Response) > 0){
Reduced_ThreePlus$Response = log(Reduced_ThreePlus$Response)  
}else{
Reduced_ThreePlus$Response = log(Reduced_ThreePlus$Response+1)  
}}
  
##If Power then
if(grepl("Power", GoI_X, fixed = TRUE) == T){
GetPower = extract_numeric(GoI_X)
Reduced_ThreePlus$Response = Reduced_ThreePlus$Response^GetPower
}

##If binned (each bin makes up a fixed % n, different no. samples in each bin)
if(grepl("Binned", GoI_X, fixed = TRUE) == T){
GetBins = extract_numeric(GoI_X)
Reduced_ThreePlus$Response = cut(Reduced_ThreePlus$Response, breaks = GetBins, labels = c(seq(1, GetBins, 1)))
Reduced_ThreePlus$Response = as.numeric(Reduced_ThreePlus$Response)
}    
##If Ntiled (each bin the same size)
if(grepl("Ntile", GoI_X, fixed = TRUE) == T){
GetNtile = extract_numeric(GoI_X)
Reduced_ThreePlus$Response = ntile(Reduced_ThreePlus$Response, GetNtile)
}      
}  
##########


########## RUN MODELS ##########
ModelList = list()
p2 = gsub(" ", "", gsub("-", "_", gsub(">=", "", GoI)))
ModelList[["Linear"]] = lm(Response~U+S+L+R+P, Reduced_ThreePlus)
ModelList[["Two Way"]] = lm(Response~(U+S+L+R+P)^2, Reduced_ThreePlus)
##########


TEST1 = anova(ModelList[["Linear"]] , ModelList[["Two Way"]])
FStat = as.data.frame(c(TEST1[[6]][[2]]))
colnames(FStat) = c("Linear-TwoWay")
FStat$Exp = GoI
write.csv(FStat, paste(FilePath, GoI_X, "_FStats.csv", sep=""))
########## PULL AVP, STATS AND COEFS ##########
AllAVP_GoI = as.data.frame(matrix(ncol = 10, nrow=0))
colnames(AllAVP_GoI) = c("Combo", "U", "S", "L", "R", "P", "Response", "Predicted", "ModelType", "Exp")

AllCoefs_GoI = as.data.frame(matrix(ncol = 8, nrow=0))
colnames(AllCoefs_GoI) = c("term", "estimate", "std.error", "statistic", "p.value", "Sig", "ModelType", "Exp")


ModelStats_GoI = as.data.frame(matrix(ncol = 19, nrow=0))
colnames(ModelStats_GoI) = c("r.squared", "adj.r.squared", "sigma", "statistic", "p.value", "df", "logLik", "AIC", "BIC", "deviance", "df.residual", "nobs", "NCV", "SW_Input", "SW_Residuals", "LOOCV", "BPTest", "ModelType", "Exp")


for(z in c("Linear", "Two Way")){
#AVP
GetPredicted = as.data.frame(ModelList[[z]]$fitted.values)
ActvPred = as.data.frame(cbind(Reduced_ThreePlus, GetPredicted$`ModelList[[z]]$fitted.values`))
colnames(ActvPred) = c(colnames(Reduced_ThreePlus), "Predicted")
ActvPred$ModelType = z
ActvPred$Exp = GoI
AllAVP_GoI = rbind(AllAVP_GoI, ActvPred)
write.csv(AllAVP_GoI, paste(FilePath, GoI_X, "_3Models_AVP.csv", sep=""))

#COEFS
Coefs = tidy(ModelList[[z]])
Coefs = Coefs[-1, ] #####Remove Intercept
Coefs$term = gsub(":", "+", Coefs$term)
Coefs$term = factor(Coefs$term, levels=rev(Coefs$term))
Coefs$Sig <- ifelse(Coefs$p.value <0.05,  "*", NA)
Coefs$ModelType = z
Coefs$Exp = z
Coefs$term = factor(Coefs$term, levels = rev(Coefs$term))
AllCoefs_GoI = rbind(AllCoefs_GoI, Coefs)
write.csv(AllCoefs_GoI, paste(FilePath, GoI_X, "_3Models_Coefs.csv", sep=""))


#Stats
Stats = glance(ModelList[[z]])
CheckNCV =  tryCatch(ncvTest(ModelList[[z]]), error=function(err) NA)
if(is.logical(CheckNCV)== T){Stats$NCV = "NA"}else{Stats$NCV = CheckNCV[[5]]}
Stats$SW_Input = shapiro.test(Reduced_ThreePlus$Response)[[2]]
CheckSWR =  tryCatch(shapiro.test(residuals(ModelList[[z]])), error=function(err) NA)
if(is.logical(CheckSWR)== T){Stats$SW_Residuals = "NA"}else{Stats$SW_Residuals = CheckSWR[[2]]}
Stats$LOOCV = calc_loocv_rmse(ModelList[[z]])
Stats$BPTest =  bptest(ModelList[[z]])[[4]]
Stats$ModelType = z
Stats$Exp = GoI
ModelStats_GoI = rbind(ModelStats_GoI, Stats)
write.csv(ModelStats_GoI, paste(FilePath, GoI_X, "_3Models_Stats.csv", sep=""))
}
##########


########## PANEL II - AVP ##########    
PullBRANNData = subset(BRANN_AvP, BRANN_AvP$Exp %in% GoI_X)
PullAvP = AllAVP_GoI[, c("Response", "Predicted", "Exp", "ModelType")]
FourModels = rbind(PullBRANNData, PullAvP)

GEXPanel[[paste(GoI_X, "_ii_Models", sep="")]] = ggplot(FourModels, aes(x=Response, y=Predicted)) + geom_point(aes(color = ModelType)) + xlab("Actual") + theme_classic() + geom_smooth(aes(color = ModelType), method = lm, se = FALSE, fullrange = TRUE) + theme(legend.position="none", legend.title = element_blank(), plot.title = element_text(face="bold"), axis.title = element_text(size = 8), axis.text = element_text(size = 8)) + scale_color_manual(values = c(BRANN = ColourBRANN,  "Linear" = ColourLinear, "Two Way" = ColourTwoWay))+ ggtitle("Morphology score") 

########## PANEL III - LINEAR COEFS ##########
GoI_Linear_Coefs = subset(AllCoefs_GoI, AllCoefs_GoI$ModelType %in% "Linear")
GoI_Linear_Coefs$term = factor(GoI_Linear_Coefs$term, levels = c("U", "S", "L", "R", "P"))

GEXPanel[[paste(GoI_X, "_iii_LinearCoefs", sep="")]] = ggplot(GoI_Linear_Coefs, aes(x=term, y=estimate)) + geom_col(fill = ColourLinear, color = "#000000", position = position_dodge(width = 0.9), width = 0.9)  +theme_classic() + geom_hline(yintercept=0)+ ylab("Coefficient") + xlab("") + geom_errorbar(aes(ymin = estimate-std.error, ymax = estimate+std.error, ), position = position_dodge(width = 0.9), width = 0.2) + ggtitle("") + geom_point( aes(shape = Sig, y = estimate + sign(estimate) * (std.error + (std.error*0.5))), position = position_dodge(width = 0.9), size = 1, show.legend = F) + scale_shape_manual(values=c(8)) + theme(axis.title = element_text(size = 8), axis.text.y = element_text(size = 8), axis.text.x = element_text(size = 8, face = "bold"))

########## PANEL IV - TWO-WAY COEFS ##########
GoI_TwoWay_Coefs = subset(AllCoefs_GoI, AllCoefs_GoI$ModelType %in% "Two Way")
GoI_TwoWay_Coefs$term = factor(GoI_TwoWay_Coefs$term, levels = c("U", "S", "L", "R", "P", "U+S", "U+L", "U+R", "U+P", "S+L", "S+R", "S+P", "L+R", "L+P", "R+P"))

GEXPanel[[paste(GoI_X, "_iii_TwoWayCoefs", sep="")]] = ggplot(GoI_TwoWay_Coefs, aes(x=term, y=estimate)) + geom_col(fill = ColourTwoWay, color = "#000000", position = position_dodge(width = 0.9), width = 0.9)  +theme_classic() + geom_hline(yintercept=0)+ ylab("Coefficient") + xlab("") + geom_errorbar(aes(ymin = estimate-std.error, ymax = estimate+std.error, ), position = position_dodge(width = 0.9), width = 0.2) + ggtitle("") + geom_point( aes(shape = Sig, y = estimate + sign(estimate) * (std.error + (std.error*0.5))), position = position_dodge(width = 0.9), size = 1, show.legend = F) + scale_shape_manual(values=c(8))+ theme(axis.title = element_text(size = 8), axis.text.y = element_text(size = 8), axis.text.x = element_text(size = 8, face = "bold"))
}

########## 3C-E: EMERGENT PROPERTIES ##########

#TRANSFORMATION OPTIONS
## Exp_Log - Logs data. If the data contains 0 then it will add 1 before logging.
## Exp_Power_n - Raises data to the power of n. Use 0.5 to get square root
## Exp_Binned_n - Categorized into bins of a fixed % of the distribution, different no. samples in each bin. n is the number of bins
## Exp_Ntile_n - Categorized into bins of a fixed % of the sample size, same no. samples in each bin. n is the number of bins
#FontSizes = 8
#"CellNoNorm_Log", "CellNoNorm_Power_2", #, "Prolif", "CellNo.Norm", "Apoptosis
scientific_10 <- function(x) {
  #parse(text= gsub("\\+", "", gsub("\\+0", "%*%10^", gsub(" ", "", scales::scientific_format(digits=2)(x)))))
  parse(text= gsub("e\\+", "%*%10^", gsub("e\\+0", "%*%10^", gsub(" ", "", gsub("−", "-", scales::scientific_format(digits=2)(x))))))
} 
Data_To_Plot = c("CellNoNorm",  "Prolif_Power_6", "Apoptosis_Log", "Prolif_Ntile_8")# "CellNoNorm", "Apoptosis_Log", "Prolif_Power_6") 
FiveWaySupplemental = list()
NRows = length(Data_To_Plot)
for(GoI_X in Data_To_Plot){ 
GoI = gsub("_.*", "", GoI_X)
if(GoI == "Apoptosis"){
PlotTitle = "Apoptosis"
Control_Ylab = "% Annexin V+"
errormargin = 2.5
}
if(GoI == "Prolif"){
PlotTitle = "Proliferation"
Control_Ylab = "% BrdU +"
errormargin = 3

}
if(GoI == "CellNoNorm"){
PlotTitle = "Cell number"
Control_Ylab = "Fold change"
errormargin = 2.8
}


########## DATA PREP ##########
SingleMetric_AllData = as.data.frame(matrix(ncol=9, nrow=0))
colnames(SingleMetric_AllData) = c("Name", "Combo", "U", "S", "L", "R", "P", "Day", GoI)
for(x in c(2,4,6)){
SingleMetric_SingleDay = AllVariables[, c("Name", "Combo", "U", "S", "L", "R", "P", paste(GoI, x, sep="_"))]
SingleMetric_SingleDay$Day = x
colnames(SingleMetric_SingleDay) = gsub("_.*", "", colnames(SingleMetric_SingleDay))
SingleMetric_AllData = rbind(SingleMetric_AllData, SingleMetric_SingleDay)
}
SingleMetric_AllData = na.omit(SingleMetric_AllData)
SingleMetric_AllData$Name = NULL
SingleMetric_AllData$Response = SingleMetric_AllData[[GoI]]
SingleMetric_AllData[[GoI]] = NULL


SingleMetric_AllData$Combo = paste("Day", SingleMetric_AllData$Day, "_", SingleMetric_AllData$Combo, sep="")
Reduced = SingleMetric_AllData %>% group_by(Combo) %>% summarise_all(funs(mean))

Reduced$Day2 =  ifelse(Reduced$Day == 2,  1, 0)
Reduced$Day4 =  ifelse(Reduced$Day == 4,  1, 0)
Reduced$Day6 =  ifelse(Reduced$Day == 6,  1, 0)
Reduced$Day = NULL

GetReps = as.data.frame(table(SingleMetric_AllData$Combo))
ThreePlusReps = subset(GetReps, GetReps$Freq >=3)
Reduced_ThreePlus = subset(Reduced, Reduced$Combo %in% ThreePlusReps$Var1)
##########

########## APPLY TRANSFORMATIONS IF REQUIRED ##########
if(GoI_X %notin% GoI){
#If log then  
if(grepl("Log", GoI_X, fixed = TRUE) == T){
if(min(Reduced_ThreePlus$Response) > 0){
Reduced_ThreePlus$Response = log(Reduced_ThreePlus$Response)  
}else{
Reduced_ThreePlus$Response = log(Reduced_ThreePlus$Response+1)  
}}
  
##If Power then
if(grepl("Power", GoI_X, fixed = TRUE) == T){
GetPower = extract_numeric(GoI_X)
Reduced_ThreePlus$Response = Reduced_ThreePlus$Response^GetPower
}

##If binned (each bin makes up a fixed % n, different no. samples in each bin)
if(grepl("Binned", GoI_X, fixed = TRUE) == T){
GetBins = extract_numeric(GoI_X)
Reduced_ThreePlus$Response = cut(Reduced_ThreePlus$Response, breaks = GetBins, labels = c(seq(1, GetBins, 1)))
Reduced_ThreePlus$Response = as.numeric(Reduced_ThreePlus$Response)
}    
##If Ntiled (each bin the same size)
if(grepl("Ntile", GoI_X, fixed = TRUE) == T){
GetNtile = extract_numeric(GoI_X)
Reduced_ThreePlus$Response = ntile(Reduced_ThreePlus$Response, GetNtile)
}      
}  
##########

########## RUN MODELS ##########
ModelList = list()
p2 = gsub(" ", "", gsub("-", "_", gsub(">=", "", GoI)))
ModelList[["Linear"]] = lm(Response~U+S+L+R+P+Day2+Day4+Day6, Reduced_ThreePlus)
ModelList[["Two Way"]] = lm(Response~Day2+Day4+Day6+(U+S+L+R+P)^2, Reduced_ThreePlus)
ModelList[["Five Way"]] = lm(Response~Day2+Day4+Day6+(U+S+L+R+P)^5, Reduced_ThreePlus)
##########

##Calc F-stats
ModelList[["Three Way"]] = lm(Response~Day2+Day4+Day6+(U+S+L+R+P)^3, Reduced_ThreePlus)
ModelList[["Four Way"]] = lm(Response~Day2+Day4+Day6+(U+S+L+R+P)^4, Reduced_ThreePlus)

TEST1 = anova(ModelList[["Linear"]] , ModelList[["Two Way"]])
TEST2 = anova(ModelList[["Linear"]] , ModelList[["Three Way"]])
TEST3 = anova(ModelList[["Linear"]] , ModelList[["Four Way"]])
TEST4 = anova(ModelList[["Linear"]] , ModelList[["Five Way"]])
TEST5 = anova(ModelList[["Two Way"]], ModelList[["Three Way"]])
TEST6 = anova(ModelList[["Three Way"]], ModelList[["Four Way"]])
TEST7 = anova(ModelList[["Four Way"]], ModelList[["Five Way"]])
TEST8 = anova(ModelList[["Two Way"]], ModelList[["Five Way"]])

FStat = as.data.frame(t(c(TEST1[[6]][[2]], TEST2[[6]][[2]], TEST3[[6]][[2]], TEST4[[6]][[2]], TEST5[[6]][[2]], TEST6[[6]][[2]], TEST7[[6]][[2]], TEST8[[6]][[2]])))
colnames(FStat) = c("Linear-TwoWay", "Linear-ThreeWay", "Linear-FourWay", "Linear-FiveWay", "TwoWay-ThreeWay", "ThreeWay-FourWay", "FourWay-FiveWay", "TwoWay-FiveWay")
FStat$Exp = GoI
write.csv(FStat, paste(FilePath, GoI_X, "_FStats.csv", sep=""))
ModelList[["Three Way"]] = NULL
ModelList[["Four Way"]] = NULL

########## PULL AVP, STATS AND COEFS ##########
AllAVP_GoI = as.data.frame(matrix(ncol = 13, nrow=0))
colnames(AllAVP_GoI) = c("Combo", "U", "S", "L", "R", "P", "Response", "Day2" , "Day4", "Day6", "Predicted", "ModelType", "Exp")

AllCoefs_GoI = as.data.frame(matrix(ncol = 8, nrow=0))
colnames(AllCoefs_GoI) = c("term", "estimate", "std.error", "statistic", "p.value", "Sig", "ModelType", "Exp")


ModelStats_GoI = as.data.frame(matrix(ncol = 19, nrow=0))
colnames(ModelStats_GoI) = c("r.squared", "adj.r.squared", "sigma", "statistic", "p.value", "df", "logLik", "AIC", "BIC", "deviance", "df.residual", "nobs", "NCV", "SW_Input", "SW_Residuals", "LOOCV", "BPTest", "ModelType", "Exp")


for(z in c("Linear", "Two Way")){ #, "Five Way"
#AVP
GetPredicted = as.data.frame(ModelList[[z]]$fitted.values)
ActvPred = as.data.frame(cbind(Reduced_ThreePlus, GetPredicted$`ModelList[[z]]$fitted.values`))
colnames(ActvPred) = c(colnames(Reduced_ThreePlus), "Predicted")
ActvPred$ModelType = z
ActvPred$Exp = GoI
AllAVP_GoI = rbind(AllAVP_GoI, ActvPred)
write.csv(AllAVP_GoI, paste(FilePath, GoI_X, "_3Models_AVP.csv", sep=""))

#COEFS
Coefs = tidy(ModelList[[z]])
Coefs = Coefs[-1, ] #####Remove Intercept
Coefs$term = gsub(":", "+", gsub("Day", "D", Coefs$term))
Coefs$Sig <- ifelse(Coefs$p.value <0.05,  "*", NA)
Coefs$ModelType = z
Coefs$Exp = z
AllCoefs_GoI = rbind(AllCoefs_GoI, Coefs)
write.csv(AllCoefs_GoI, paste(FilePath, GoI_X, "_3Models_Coefs.csv", sep=""))


#Stats
Stats = glance(ModelList[[z]])
CheckNCV =  tryCatch(ncvTest(ModelList[[z]]), error=function(err) NA)
if(is.logical(CheckNCV)== T){Stats$NCV = "NA"}else{Stats$NCV = CheckNCV[[5]]}
Stats$SW_Input = shapiro.test(Reduced_ThreePlus$Response)[[2]]
CheckSWR =  tryCatch(shapiro.test(residuals(ModelList[[z]])), error=function(err) NA)
if(is.logical(CheckSWR)== T){Stats$SW_Residuals = "NA"}else{Stats$SW_Residuals = CheckSWR[[2]]}
Stats$LOOCV = calc_loocv_rmse(ModelList[[z]])
Stats$BPTest =  bptest(ModelList[[z]])[[4]]
Stats$ModelType = z
Stats$Exp = GoI
ModelStats_GoI = rbind(ModelStats_GoI, Stats)
write.csv(ModelStats_GoI, paste(FilePath, GoI_X, "_3Models_Stats.csv", sep=""))
}
##########


########## PANEL II - AVP ##########    #Add BRANN
PullBRANNData = subset(BRANN_AvP, BRANN_AvP$Exp %in% GoI_X)
PullAvP = AllAVP_GoI[, c("Response", "Predicted", "Exp", "ModelType")]
FourModels = rbind(PullBRANNData, PullAvP)


if(GoI == "Prolif"){
  GEXPanel[[paste(GoI_X, "_ii_Models", sep="")]] = ggplot(FourModels, aes(x=Response, y=Predicted)) + geom_point(aes(color = ModelType)) + xlab("Actual") + theme_classic() + geom_smooth(aes(color = ModelType), method = lm, se = FALSE, fullrange = TRUE) + theme(axis.title = element_text(size = 8), axis.text.y = element_text(size = 8), axis.text.x = element_text(size = 8, face = "bold"), legend.position="none", legend.title = element_blank(), plot.title = element_text(face="bold")) + scale_color_manual(values = c(BRANN = ColourBRANN, "Five Way" = ColourFiveWay, "Linear" = ColourLinear, "Two Way" = ColourTwoWay)) +scale_y_continuous(label=scientific_10) +scale_x_continuous(label=scientific_10) + ggtitle(PlotTitle)
}else{
GEXPanel[[paste(GoI_X, "_ii_Models", sep="")]] = ggplot(FourModels, aes(x=Response, y=Predicted)) + geom_point(aes(color = ModelType)) + xlab("Actual") + theme_classic() + geom_smooth(aes(color = ModelType), method = lm, se = FALSE, fullrange = TRUE) + theme(axis.title = element_text(size = 8), axis.text = element_text(size = 8), legend.position="none", legend.title = element_blank(), plot.title = element_text(face="bold")) + scale_color_manual(values = c(BRANN = ColourBRANN, "Five Way" = ColourFiveWay, "Linear" = ColourLinear, "Two Way" = ColourTwoWay))+ ggtitle(PlotTitle) 
}

########## PANEL III - LINEAR COEFS ##########
GoI_Linear_Coefs = subset(AllCoefs_GoI, AllCoefs_GoI$ModelType %in% "Linear")
GoI_Linear_Coefs$term = factor(GoI_Linear_Coefs$term, levels = c("D2", "D4", "D6", "U", "S", "L", "R", "P"))


if(GoI == "Prolif"){
GEXPanel[[paste(GoI_X, "_iii_LinearCoefs", sep="")]] = ggplot(GoI_Linear_Coefs, aes(x=term, y=estimate)) + geom_col(fill = ColourLinear, color = "#000000", position = position_dodge(width = 0.9), width = 0.9)  +theme_classic() + geom_hline(yintercept=0)+ ylab("Coefficient") + xlab("") + geom_errorbar(aes(ymin = estimate-std.error, ymax = estimate+std.error, ), position = position_dodge(width = 0.9), width = 0.2) + ggtitle("") + geom_point( aes(shape = Sig, y = estimate + sign(estimate) * (std.error + (std.error*0.5))), position = position_dodge(width = 0.9), size = 1, show.legend = F) + scale_shape_manual(values=c(8))+ scale_x_discrete(labels = function(x) str_wrap(x, width = 3))+scale_y_continuous(label=scientific_10)+ theme(axis.title = element_text(size = 8), axis.text.y = element_text(size = 8), axis.text.x = element_text(size = 8, face = "bold"))
}else{
GEXPanel[[paste(GoI_X, "_iii_LinearCoefs", sep="")]] = ggplot(GoI_Linear_Coefs, aes(x=term, y=estimate)) + geom_col(fill = ColourLinear, color = "#000000", position = position_dodge(width = 0.9), width = 0.9)  +theme_classic() + geom_hline(yintercept=0)+ ylab("Coefficient") + xlab("") + geom_errorbar(aes(ymin = estimate-std.error, ymax = estimate+std.error, ), position = position_dodge(width = 0.9), width = 0.2) + ggtitle("") + geom_point( aes(shape = Sig, y = estimate + sign(estimate) * (std.error + (std.error*0.5))), position = position_dodge(width = 0.9), size = 1, show.legend = F) + scale_shape_manual(values=c(8))+ scale_x_discrete(labels = function(x) str_wrap(x, width = 3))+ theme(axis.title = element_text(size = 8), axis.text.y = element_text(size = 8), axis.text.x = element_text(size = 8, face = "bold"))
}

########## PANEL IV - TWO-WAY COEFS ##########
GoI_TwoWay_Coefs = subset(AllCoefs_GoI, AllCoefs_GoI$ModelType %in% "Two Way")
GoI_TwoWay_Coefs$term = factor(GoI_TwoWay_Coefs$term, levels = c("D2", "D4", "D6", "U", "S", "L", "R", "P", "U+S", "U+L", "U+R", "U+P", "S+L", "S+R", "S+P", "L+R", "L+P", "R+P"))

if(GoI == "Prolif"){
GEXPanel[[paste(GoI_X, "_iii_TwoWayCoefs", sep="")]] = ggplot(GoI_TwoWay_Coefs, aes(x=term, y=estimate)) + geom_col(fill = ColourTwoWay, color = "#000000", position = position_dodge(width = 0.9), width = 0.9)  +theme_classic() + geom_hline(yintercept=0)+ ylab("Coefficient") + xlab("") + geom_errorbar(aes(ymin = estimate-std.error, ymax = estimate+std.error, ), position = position_dodge(width = 0.9), width = 0.2) + ggtitle("") + geom_point( aes(shape = Sig, y = estimate + sign(estimate) * (std.error + (std.error*0.5))), position = position_dodge(width = 0.9), size = 1, show.legend = F) + scale_shape_manual(values=c(8))+ scale_x_discrete(labels = function(x) str_wrap(x, width = 3)) +scale_y_continuous(label=scientific_10)+ theme(axis.title = element_text(size = 8), axis.text.y = element_text(size = 8), axis.text.x = element_text(size = 8, face = "bold"))
}else{
 GEXPanel[[paste(GoI_X, "_iii_TwoWayCoefs", sep="")]] = ggplot(GoI_TwoWay_Coefs, aes(x=term, y=estimate)) + geom_col(fill = ColourTwoWay, color = "#000000", position = position_dodge(width = 0.9), width = 0.9)  +theme_classic() + geom_hline(yintercept=0)+ ylab("Coefficient") + xlab("") + geom_errorbar(aes(ymin = estimate-std.error, ymax = estimate+std.error, ), position = position_dodge(width = 0.9), width = 0.2) + ggtitle("") + geom_point( aes(shape = Sig, y = estimate + sign(estimate) * (std.error + (std.error*0.5))), position = position_dodge(width = 0.9), size = 1, show.legend = F) + scale_shape_manual(values=c(8))+ scale_x_discrete(labels = function(x) str_wrap(x, width = 3))+ theme(axis.title = element_text(size = 8), axis.text.y = element_text(size = 8), axis.text.x = element_text(size = 8, face = "bold"))
 
}


########## FOR SUPPLEMENTAL - FIVE-WAY COEFS ##########
#GoI_FiveWay_Coefs = subset(AllCoefs_GoI, AllCoefs_GoI$ModelType %in% "Five Way")
#GoI_FiveWay_Coefs$term = factor(GoI_FiveWay_Coefs$term, levels = c("D2", "D4", "D6", "U", "S", "L", "R", "P", "U+S", "U+L", "U+R", "U+P", "S+L", "S+R", "S+P", "L+R", "L+P", "R+P", "U+S+L", "U+S+R", "U+S+P", "U+L+R","U+L+P", "U+R+P", "S+L+R", "S+L+P", "S+R+P", "L+R+P", "U+S+L+R", "U+S+L+P", "U+S+R+P", "U+L+R+P", "S+L+R+P", "U+S+L+R+P"))

#FiveWaySupplemental[[paste(GoI_X, "_FiveWayCoefs", sep="")]] = ggplot(GoI_FiveWay_Coefs, aes(x=term, y=estimate)) + geom_col(fill = ColourFiveWay, color = "#000000", position = position_dodge(width = 0.9), width = 0.9)  +theme_classic() + geom_hline(yintercept=0)+ ylab(Control_Ylab) + xlab("") + geom_errorbar(aes(ymin = estimate-std.error, ymax = estimate+std.error, ), position = position_dodge(width = 0.9), width = 0.2) + ggtitle("") + geom_point( aes(shape = Sig, y = estimate + sign(estimate) * (std.error + (std.error*0.5))), position = position_dodge(width = 0.9), size = 1, show.legend = F) + scale_shape_manual(values=c(8))+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), plot.title = element_text(face = "bold", size = 15)) + ggtitle(PlotTitle)
}

if( "Prolif_Ntile_8" %in% Data_To_Plot){
AltModelForSup = ggarrange(plotlist = list(GEXPanel[["Prolif_Ntile_8_ii_Models"]],GEXPanel[["Prolif_Ntile_8_iii_LinearCoefs"]],GEXPanel[["Prolif_Ntile_8_iii_TwoWayCoefs"]]), ncol = 3, nrow=NRows, widths = rep(c(0.85, 0.85, 1.7), NRows))
pdf(paste(FilePath, "Figure_S8_Prolif.pdf", sep=""), width = 15, height = NRows*4)
print(AltModelForSup)
dev.off()
GEXPanel[["Prolif_Ntile_8_ii_Models"]]=NULL; GEXPanel[["Prolif_Ntile_8_iii_LinearCoefs"]]=NULL; GEXPanel[["Prolif_Ntile_8_iii_TwoWayCoefs"]]=NULL
}

Figure3 = ggarrange(plotlist = GEXPanel, ncol = 3, nrow=4, widths = rep(c(0.85, 0.85, 1.7), 4), align = "hv")
pdf(paste(FilePath, "Figure3BCDE_Models.pdf", sep=""), width = 12, height = 4*2.5)
print(Figure3)
dev.off()
```

### FIGURE 4 + S10: Gene Expression Models
```{r}
Data_To_Plot = c("Rex1", "Oct4", "Dnmt3b", "Fgf5",  "Lefty2", "Otx2", "Mixl1") 
GEXPanel = list()
NRows = length(Data_To_Plot)

for(GoI in Data_To_Plot){

########## DATA PREP ##########
SingleMetric_AllData =  AllVariables[, c("Name", "Combo", "U", "S", "L", "R", "P", GoI)]
SingleMetric_AllData$Response = SingleMetric_AllData[[GoI]]
SingleMetric_AllData[[GoI]] = NULL
SingleMetric_AllData = na.omit(SingleMetric_AllData)

SingleMetric_AllData$Name = NULL
SingleMetric_AllData$Combo = paste("Day", SingleMetric_AllData$Day, "_", SingleMetric_AllData$Combo, sep="")
Reduced = SingleMetric_AllData %>% group_by(Combo) %>% summarise_all(funs(mean))

GetReps = as.data.frame(table(SingleMetric_AllData$Combo))
ThreePlusReps = subset(GetReps, GetReps$Freq >=3)
ReducedData_ThreePlus = subset(Reduced, Reduced$Combo %in% ThreePlusReps$Var1)
##########

########## RUN MODELS ##########
ModelList = list()
p2 = gsub(" ", "", gsub("-", "_", gsub(">=", "", GoI)))
ModelList[["Linear"]] = lm(Response~U+S+L+R+P, ReducedData_ThreePlus)
ModelList[["Two Way"]] = lm(Response~(U+S+L+R+P)^2, ReducedData_ThreePlus)
##########
TEST1 = anova(ModelList[["Linear"]] , ModelList[["Two Way"]])
FStat = as.data.frame(c(TEST1[[6]][[2]]))
colnames(FStat) = c("Linear-TwoWay")
FStat$Exp = GoI
write.csv(FStat, paste(FilePath, GoI, "_FStats.csv", sep=""))
########## PULL AVP, STATS AND COEFS ##########
AllAVP_GoI = as.data.frame(matrix(ncol = 10, nrow=0))
colnames(AllAVP_GoI) = c("Combo", "U", "S", "L", "R", "P", "Response", "Predicted", "ModelType", "Exp")

AllCoefs_GoI = as.data.frame(matrix(ncol = 8, nrow=0))
colnames(AllCoefs_GoI) = c("term", "estimate", "std.error", "statistic", "p.value", "Sig", "ModelType", "Exp")


ModelStats_GoI = as.data.frame(matrix(ncol = 19, nrow=0))
colnames(ModelStats_GoI) = c("r.squared", "adj.r.squared", "sigma", "statistic", "p.value", "df", "logLik", "AIC", "BIC", "deviance", "df.residual", "nobs", "NCV", "SW_Input", "SW_Residuals", "LOOCV", "BPTest", "ModelType", "Exp")


for(z in c("Linear", "Two Way")){
#AVP
GetPredicted = as.data.frame(ModelList[[z]]$fitted.values)
ActvPred = as.data.frame(cbind(ReducedData_ThreePlus, GetPredicted$`ModelList[[z]]$fitted.values`))
colnames(ActvPred) = c(colnames(ReducedData_ThreePlus), "Predicted")
ActvPred$ModelType = z
ActvPred$Exp = GoI
AllAVP_GoI = rbind(AllAVP_GoI, ActvPred)
write.csv(AllAVP_GoI, paste(FilePath, GoI, "_3Models_AVP.csv", sep=""))

#COEFS
Coefs = tidy(ModelList[[z]])
Coefs = Coefs[-1, ] #####Remove Intercept
Coefs$term = gsub(":", "+", Coefs$term)
Coefs$term = factor(Coefs$term, levels=rev(Coefs$term))
Coefs$Sig <- ifelse(Coefs$p.value <0.05,  "*", NA)
Coefs$ModelType = z
Coefs$Exp = z
Coefs$term = factor(Coefs$term, levels = rev(Coefs$term))
AllCoefs_GoI = rbind(AllCoefs_GoI, Coefs)
write.csv(AllCoefs_GoI, paste(FilePath, GoI, "_3Models_Coefs.csv", sep=""))


#Stats
Stats = glance(ModelList[[z]])
CheckNCV =  tryCatch(ncvTest(ModelList[[z]]), error=function(err) NA)
if(is.logical(CheckNCV)== T){Stats$NCV = "NA"}else{Stats$NCV = CheckNCV[[5]]}
Stats$SW_Input = shapiro.test(ReducedData_ThreePlus$Response)[[2]]
CheckSWR =  tryCatch(shapiro.test(residuals(ModelList[[z]])), error=function(err) NA)
if(is.logical(CheckSWR)== T){Stats$SW_Residuals = "NA"}else{Stats$SW_Residuals = CheckSWR[[2]]}
Stats$LOOCV = calc_loocv_rmse(ModelList[[z]])
Stats$BPTest =  bptest(ModelList[[z]])[[4]]
Stats$ModelType = z
Stats$Exp = GoI
ModelStats_GoI = rbind(ModelStats_GoI, Stats)
write.csv(ModelStats_GoI, paste(FilePath, GoI, "_3Models_Stats.csv", sep=""))
}
##########


########## PANEL II - AVP ##########    
PullBRANNData = subset(BRANN_AvP, BRANN_AvP$Exp %in% GoI)
PullAvP = AllAVP_GoI[, c("Response", "Predicted", "Exp", "ModelType")]
FourModels = rbind(PullBRANNData, PullAvP)

GEXPanel[[paste(GoI, "_ii_Models", sep="")]] = ggplot(FourModels, aes(x=Response, y=Predicted)) + geom_point(aes(color = ModelType)) + xlab("Actual") + theme_classic() + geom_smooth(aes(color = ModelType), method = lm, se = FALSE, fullrange = TRUE) + theme(legend.position="none", legend.title = element_blank(), plot.title = element_text(face ="bold.italic"), axis.title = element_text(size = 8), axis.text = element_text(size = 8)) + scale_color_manual(values = c(BRANN = ColourBRANN,  "Linear" = ColourLinear, "Two Way" = ColourTwoWay) ) + ggtitle(GoI)

########## PANEL III - LINEAR COEFS ##########
GoI_Linear_Coefs = subset(AllCoefs_GoI, AllCoefs_GoI$ModelType %in% "Linear")
GoI_Linear_Coefs$term = factor(GoI_Linear_Coefs$term, levels = c("U", "S", "L", "R", "P"))

GEXPanel[[paste(GoI, "_iii_LinearCoefs", sep="")]] = ggplot(GoI_Linear_Coefs, aes(x=term, y=estimate)) + geom_col(fill = ColourLinear, color = "#000000", position = position_dodge(width = 0.9), width = 0.9)  +theme_classic() + geom_hline(yintercept=0)+ ylab("Coefficient") + xlab("") + geom_errorbar(aes(ymin = estimate-std.error, ymax = estimate+std.error, ), position = position_dodge(width = 0.9), width = 0.2) + ggtitle("") + geom_point( aes(shape = Sig, y = estimate + sign(estimate) * (std.error + (std.error*0.5))), position = position_dodge(width = 0.9), size = 1, show.legend = F) + scale_shape_manual(values=c(8)) + theme(axis.title = element_text(size = 8), axis.text.x = element_text(size = 8, face = "bold"), axis.text.y = element_text(size = 8))

########## PANEL IV - TWO-WAY COEFS ##########
GoI_TwoWay_Coefs = subset(AllCoefs_GoI, AllCoefs_GoI$ModelType %in% "Two Way")
GoI_TwoWay_Coefs$term = factor(GoI_TwoWay_Coefs$term, levels = c("U", "S", "L", "R", "P", "U+S", "U+L", "U+R", "U+P", "S+L", "S+R", "S+P", "L+R", "L+P", "R+P"))

GEXPanel[[paste(GoI, "_iii_TwoWayCoefs", sep="")]] = ggplot(GoI_TwoWay_Coefs, aes(x=term, y=estimate)) + geom_col(fill = ColourTwoWay, color = "#000000", position = position_dodge(width = 0.9), width = 0.9)  +theme_classic() + geom_hline(yintercept=0)+ ylab("Coefficient") + xlab("") + geom_errorbar(aes(ymin = estimate-std.error, ymax = estimate+std.error, ), position = position_dodge(width = 0.9), width = 0.2) + ggtitle("") + geom_point( aes(shape = Sig, y = estimate + sign(estimate) * (std.error + (std.error*0.5))), position = position_dodge(width = 0.9), size = 1, show.legend = F) + scale_shape_manual(values=c(8))+ theme(axis.title = element_text(size = 8), axis.text.x = element_text(size = 8, face = "bold"), axis.text.y = element_text(size = 8))
}

GEXPanel_AltMain = GEXPanel
GEXPanel_AltSupp = list()
for(x in c("Rex1", "Oct4", "Dnmt3b", "Fgf5",  "Lefty2", "Otx2", "Mixl1")){
GEXPanel_AltSupp[[paste(x, "_iii_TwoWayCoefs", sep="")]] = GEXPanel_AltMain[[paste(x, "_iii_TwoWayCoefs", sep="")]]
GEXPanel_AltMain[[paste(x, "_iii_TwoWayCoefs", sep="")]] = NULL  
}
Figure4Main = ggarrange(plotlist = GEXPanel_AltMain, ncol = 4, nrow=4, align = "hv")
Figure4Supp = ggarrange(plotlist = GEXPanel_AltSupp, ncol = 2, nrow=4,  align = "hv")

pdf(paste(FilePath, "Figure4andS10.pdf", sep= ""), width = 12, height = 4*2.5)
print(list(Figure4Main, Figure4Supp))
dev.off()
```

### FIGURE S2 + S9: Raw data bar plots - MORPHOLOGY and GENE EXPRESSION
```{r}
SuppControlPCRFigs = list()
Data_To_Plot = c("Rex1", "Oct4", "Dnmt3b", "Fgf5", "Mixl1", "Lefty2", "Otx2", "Morphology")
NRows = length(Data_To_Plot)
for(e in Data_To_Plot){

if(e == "Morphology"){
Ytitle = "Morphology Score"
TitleStyle = "bold"}else{
Ytitle =expression(Log[2]~Fold~Change)
TitleStyle = "bold.italic"}  
  
SelectData = AllVariables[, c("Combo", e)]   
colnames(SelectData) = c("Combo", "Value")
SelectData = na.omit(SelectData)



SelectData_Condensed = SelectData %>% group_by(Combo) %>% summarise(n = n(), Mean = mean(Value), stdev = sd(Value), se=sd(Value)/sqrt(n()))
SelectData_Condensed_n3 = subset(SelectData_Condensed, SelectData_Condensed$n > 1)
SelectData_Condensed$Combo = factor(SelectData_Condensed$Combo, levels = c("DMSO", "U", "S", "L", "R", "P", "U+S", "U+L", "U+R", "U+P", "S+L", "S+R", "S+P", "L+R", "L+P", "R+P", "U+S+L", "U+S+R", "U+R+P", "U+S+P","U+L+P","S+L+R", "S+L+P", "S+R+P", "L+R+P", "U+S+R+P", "U+S+L+P", "U+S+L+R+P"))

ExclLR = subset(SelectData_Condensed,  SelectData_Condensed$Combo %notin% c("L+R", "U+L+R", "S+L+R", "L+R+P", "U+S+L+R",  "U+L+R+P", "S+L+R+P",  "U+S+L+R+P"))
SelectData_ExclLR = subset(SelectData,  SelectData$Combo %notin% c("L+R", "U+L+R", "S+L+R", "L+R+P", "U+S+L+R",  "U+L+R+P", "S+L+R+P",  "U+S+L+R+P"))




ExclLR$ComboWn = paste(ExclLR$Combo, " (n = ", ExclLR$n, ")", sep="")
SelectData_ExclLRmerge = merge(ExclLR, SelectData_ExclLR, by = "Combo")

ExclLR <- ExclLR[order(ExclLR$Combo),] 
ExclLR$ComboWn = factor(ExclLR$ComboWn, levels = ExclLR$ComboWn)

SelectData_Rm = subset(SelectData, SelectData$Combo %in% ExclLR$Combo )

ANOVARes = DunnettTest(x=SelectData_Rm$Value, g=SelectData_Rm$Combo, control = "DMSO")
ANOVAResOuts = as.data.frame(ANOVARes[[1]])
ANOVAResOuts$Combo = gsub("-DMSO", "", row.names(ANOVAResOuts))
ExclLR = merge(ExclLR, ANOVAResOuts, by = "Combo", all = T)

ExclLR$Sig = ifelse(ExclLR$pval < 0.05, "*", NA)


SuppControlPCRFigs[[e]] = ggplot(ExclLR, aes(x=ComboWn, y=Mean)) + geom_col(fill = ColourNeutral, color = "#000000") + geom_point(aes(color = ColourTwoWay, shape = Sig, y = Mean + sign(Mean) * (se + (se*3.5))), position = position_dodge(width = 0.9), size = 1, show.legend = F) +theme_classic() + geom_hline(yintercept=0) + ylab(Ytitle) + xlab("") + geom_errorbar(aes(ymin = Mean-se, ymax = Mean+se), position = position_dodge(width = 0.9), width = 0.2)+ scale_shape_manual(values=c(8)) + theme(legend.position="none", plot.title = element_text(size = 15, face = TitleStyle), axis.text.x = element_text( angle = 90, vjust = 0.5, hjust=1, face = "bold")) + ggtitle(e)  + geom_point(data=SelectData_ExclLRmerge, aes(x = ComboWn, y =Value), size=0.5)

}

pdf(paste(FilePath, "FigureS2_MorphologyRaw.pdf", sep=""), width = 12, height = 2.8)
print(SuppControlPCRFigs[["Morphology"]])
dev.off()
SuppControlPCRFigs[["Morphology"]] = NULL


NRows = length(SuppControlPCRFigs)
SuppPCR = ggarrange(plotlist = SuppControlPCRFigs, ncol = 1, nrow=NRows)
pdf(paste(FilePath, "FigureS9_GeneExpressionRaw.pdf", sep=""), width = 12, height = NRows*2.8)
print(SuppPCR)
dev.off()
```

### FIGURE S3-5: Raw data bar plots - CELL NUMBER, APOPTOSIS AND PROLIFERATION
```{r}
######################################
AllVariableswZeros = AllVariables

ExclLR_All = subset(AllVariableswZeros,  AllVariableswZeros$Combo %notin% c("L+R", "U+L+R", "S+L+R", "L+R+P", "U+S+L+R",  "U+L+R+P", "S+L+R+P",  "U+S+L+R+P"))  
OnlyLR_All = subset(AllVariableswZeros,  AllVariableswZeros$Combo %in% c("L+R", "U+L+R", "S+L+R", "L+R+P", "U+S+L+R",  "U+L+R+P", "S+L+R+P",  "U+S+L+R+P"))  
OnlyLR_All[c("CellNoNorm_2", "CellNoNorm_4", "CellNoNorm_6")][is.na(OnlyLR_All[c("CellNoNorm_2", "CellNoNorm_4", "CellNoNorm_6")])] <- 0

AllVariableswZeros = rbind(OnlyLR_All, ExclLR_All)

#
#
SuppControlEmergFigs = list()
Data_To_Plot = c("Prolif_2", "Prolif_4", "Prolif_6", "Apoptosis_2", "Apoptosis_4", "Apoptosis_6", "CellNoNorm_2", "CellNoNorm_4", "CellNoNorm_6")
for(e in Data_To_Plot){
if(grepl("Apoptosis", e, fixed = TRUE) == T){
PlotTitle = "Apoptosis"
Control_Ylab = "% Annexin V+"  
}
if(grepl("Prolif", e, fixed = TRUE)){
PlotTitle = "Proliferation"
Control_Ylab = "% BrdU +"
}
if(grepl("CellNoNorm", e, fixed = TRUE)){
PlotTitle = "Cell number"
Control_Ylab = "Fold change"
}
if(grepl("Morphology", e, fixed = TRUE)){
PlotTitle = "Morphology"
Control_Ylab = "Morphology score"
}
if(grepl("2", e, fixed = TRUE)){
DayFactor = " - Day 2"
}
if(grepl("4", e, fixed = TRUE)){
DayFactor = " - Day 4"
}
if(grepl("6", e, fixed = TRUE)){
DayFactor = " - Day 6"
}
  

SelectData = AllVariableswZeros[, c("Combo", e)]   
colnames(SelectData) = c("Combo", "Value")
SelectData = na.omit(SelectData)



if(DayFactor %in% c(" - Day 4", " - Day 6")){
SelectData$Value = ifelse(SelectData$Combo %in% c("L+R", "U+L+R", "S+L+R", "L+R+P", "U+S+L+R",  "U+L+R+P", "S+L+R+P",  "U+S+L+R+P"), 0, SelectData$Value)
SelectData_Condensed = SelectData %>% group_by(Combo) %>% summarise(n = n(), Mean = mean(Value), stdev = sd(Value), se=sd(Value)/sqrt(n()))
SelectData_Condensed$n = ifelse(SelectData_Condensed$Combo %in% c("L+R", "U+L+R", "S+L+R", "L+R+P", "U+S+L+R",  "U+L+R+P", "S+L+R+P",  "U+S+L+R+P"), 0, SelectData_Condensed$n)
}else{
SelectData_Condensed = SelectData %>% group_by(Combo) %>% summarise(n = n(), Mean = mean(Value), stdev = sd(Value), se=sd(Value)/sqrt(n()))
}


#if(DayFactor == " - Day 2"){
SelectData_Condensed$LRColour = ifelse(SelectData_Condensed$Combo %in% c("L+R", "U+L+R", "S+L+R", "L+R+P", "U+S+L+R",  "U+L+R+P", "S+L+R+P",  "U+S+L+R+P"), "Blue", "Neutral")

###
SelectData_Condensed$ComboWn = paste(SelectData_Condensed$Combo, " (n = ", SelectData_Condensed$n, ")", sep="")
SelectData_merge = merge(SelectData_Condensed, SelectData, by = "Combo")

SelectData_Samples = subset(SelectData, SelectData$Combo %in% SelectData_Condensed$Combo)

PullNames = SelectData_Condensed[, c("Combo", "ComboWn")] 
SelectData_Samples = merge(SelectData_Samples, PullNames, by = "Combo")
SelectData_Condensed$ComboWn = factor(SelectData_Condensed$ComboWn, levels = SelectData_Condensed$ComboWn)

ANOVARes = DunnettTest(x=SelectData_Samples$Value, g=SelectData_Samples$Combo, control = "DMSO")
ANOVAResOuts = as.data.frame(ANOVARes[[1]])
row.names(ANOVAResOuts) = gsub("-DMSO", "", row.names(ANOVAResOuts))
ANOVAResOuts$Combo = row.names(ANOVAResOuts)

SelectData_Condensed = merge(SelectData_Condensed, ANOVAResOuts, by = "Combo", all=T)
SelectData_Condensed$Sig = ifelse(SelectData_Condensed$pval < 0.05, "*", NA)


SelectData_Condensed$Combo = factor(SelectData_Condensed$Combo, levels = c("DMSO", "U", "S", "L", "R", "P", "U+S", "U+L", "U+R", "U+P", "S+L", "S+R", "S+P", "L+R", "L+P", "R+P", "U+S+L", "U+S+R","U+L+R", "U+R+P", "U+S+P","U+L+P","S+L+R", "S+L+P", "S+R+P", "L+R+P", "U+S+R+P", "U+S+L+R", "U+S+L+P", "U+L+R+P", "S+L+R+P",  "U+S+L+R+P"))
SelectData_Condensed <- SelectData_Condensed[order(SelectData_Condensed$Combo),] 
SelectData_Condensed$ComboWn = factor(SelectData_Condensed$ComboWn, levels = unique(SelectData_Condensed$ComboWn))
SelectData_Condensed <- SelectData_Condensed[order(SelectData_Condensed$ComboWn),] 


if(e %in% c("Prolif_2", "Prolif_4", "Prolif_6")){Axis = c(0,100)}else{Axis = c(0, max(SelectData_Samples$Value)*1.2)}

SuppControlEmergFigs[[e]] = ggplot(SelectData_Condensed, aes(x=ComboWn, y=Mean,fill = LRColour)) + geom_bar(stat = "identity", color = "#000000") + scale_fill_manual(values = c("Neutral" =  ColourNeutral, "Blue" = ColourTwoWay))  +theme_classic() + geom_hline(yintercept=0) + ylab(Control_Ylab) + xlab("") + geom_errorbar(aes(ymin = Mean-se, ymax = Mean+se), position = position_dodge(width = 0.9), width = 0.2) + theme(legend.position="none", plot.title = element_text(size = 15, face = "bold"), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, face = "bold")) + ggtitle(paste(PlotTitle, DayFactor, sep = "")) + geom_point(data=SelectData_merge, aes(x = ComboWn, y =Value), color = "#000000", fill = "#000000", size = 0.5)+ geom_point(aes(color = ColourTwoWay, shape = Sig, y = Mean + sign(Mean) * (se + (se*4))), position = position_dodge(width = 0.9), size = 1, show.legend = F)+ scale_shape_manual(values=c(8))  + scale_y_continuous(limits = Axis, expand = c(0,0)) + geom_point(data=SelectData_Samples, aes(x = ComboWn, y =Value, fill = "#000000"), size=0.5)
}

SuppEmerg = ggarrange(plotlist = SuppControlEmergFigs, ncol = 1, nrow=3)
pdf(paste(FilePath, "FigureS2S4S5_EmergentPropertiesRaw.pdf", sep=""), width = 12, height = 3*2.8)
print(SuppEmerg)
dev.off()
```

### FIGURE S6: Correlation Plot
```{r}
SumForCorPlot = AllVariables %>% dplyr::select(FunctionalAssay, CellNoNorm_2, CellNoNorm_4, CellNoNorm_6, Prolif_2, Prolif_4, Prolif_6, Apoptosis_2,  Apoptosis_4, Apoptosis_6, Morphology, Rex1, Oct4, Dnmt3b, Fgf5, Mixl1, Lefty2, Otx2)
colnames(SumForCorPlot) = gsub("_", " - Day ", gsub("CellNoNorm", "Cell number", gsub("Prolif", "Proliferation", colnames(SumForCorPlot))))


CORR = mycor(SumForCorPlot)

pdf(paste(FilePath, "FigureS6A_Correlation.pdf", sep=""), width = 10, height = 8)
print(corrplot(corr=CORR$r, p.mat = CORR$p, method = "circle", diag = F, type = "upper", order = "hclust", tl.col = "black", tl.srt = 45, tl.cex = 0.7, insig="label_sig", sig.level =.05, pch.cex = 1, col=colorRampPalette(c(ColourLinear,ColourHeatmapMid, ColourHeatmapHigh))(100)))
dev.off()



###
SumForCorPlot = AllVariables %>% select(FunctionalAssay, Rex1, Oct4, Dnmt3b, Fgf5, Mixl1, Lefty2, Otx2)
colnames(SumForCorPlot) = gsub("_", " - Day ", gsub("FunctionalAssay", "Functional assay", gsub("Prolif", "Proliferation", colnames(SumForCorPlot))))

CORR = mycor(SumForCorPlot)

pdf(paste(FilePath, "FigureS6B_FACorrelation.pdf", sep=""), width = 5, height = 4)
print(corrplot(corr=CORR$r, p.mat = CORR$p, method = "circle", diag = F, type = "upper", order = "hclust", tl.col = "black", tl.srt = 45, tl.cex = 0.7, insig="label_sig", sig.level =.05, pch.cex = 1, col=colorRampPalette(c(ColourLinear,ColourHeatmapMid, ColourHeatmapHigh))(100)))
dev.off()


```



##FIGURE S7: PCA
```{r}
AllVariables2 = AllVariables

AllVariables2$U = NULL; AllVariables2$S = NULL; AllVariables2$L = NULL; AllVariables2$R = NULL; AllVariables2$P = NULL; AllVariables2$FunctionalAssay = NULL; AllVariables2$Name = NULL;  AllVariables2$CellNoRaw_2 = NULL;  AllVariables2$CellNoRaw_4 = NULL;  AllVariables2$CellNoRaw_6 = NULL
AllVariables3 = AllVariables2 %>% group_by(Combo) %>% summarise_all(mean, na.rm=T)
AllVariables3 = na.omit(AllVariables3)
RowNames = AllVariables3$Combo

AllVariables3$Combo = NULL

AllVariables_Zscore = as.data.frame(scale(AllVariables3))
row.names(AllVariables_Zscore) = RowNames

#########
set.seed(123)
OutputPCA = list()
OutputPCA[["silhouette"]] = fviz_nbclust(AllVariables_Zscore, kmeans, method = "silhouette", linecolor = ColourFiveWay, k.max = 6) +labs(title = element_blank()) + theme(axis.title = element_text(face = "bold", size = 8), axis.text = element_text(face = "bold", size = 8))
k2 <- kmeans(AllVariables_Zscore, centers = 2, nstart = 25)

OutputPCA[["Main"]] = fviz_cluster(k2, data = AllVariables_Zscore, labelsize = 6, show.clust.cent	= F) + scale_color_manual(values = c("1" = ColourLinear, "2" = ColourTwoWay)) + scale_fill_manual(values = c("1" = ColourLinear, "2" = ColourTwoWay)) +theme(legend.position = "none", plot.title = element_blank(), axis.text = element_text(face = "bold", size = 8), axis.title = element_text(face = "bold", size = 8)) #, ggtheme = theme_bw()

kmean_cluster = as.data.frame(k2$cluster)
AllVariables3 = as.data.frame(AllVariables3)
row.names(AllVariables3) = RowNames
AllVariables4 = merge(AllVariables3, kmean_cluster, by = 0)

kmean_cluster2 = subset(kmean_cluster, ! row.names(kmean_cluster) == "DMSO")
kmean_cluster2$U = ifelse(grepl("U", row.names(kmean_cluster2), fixed = T), 1, 0)
kmean_cluster2$S = ifelse(grepl("S", row.names(kmean_cluster2), fixed = T), 1, 0)
kmean_cluster2$L = ifelse(grepl("L", row.names(kmean_cluster2), fixed = T), 1, 0)
kmean_cluster2$R = ifelse(grepl("R", row.names(kmean_cluster2), fixed = T), 1, 0)
kmean_cluster2$P = ifelse(grepl("P", row.names(kmean_cluster2), fixed = T), 1, 0)

AllPercent = as.data.frame(table(kmean_cluster2$`k2$cluster`))
AllPercent$Percent = AllPercent$Freq/dim(kmean_cluster2)[1]*100
AllPercent$Freq = NULL
colnames(AllPercent) = c("Cluster", "AllPercent")



for(y in rev(c("U", "S", "L", "R", "P"))){
PullData = subset(kmean_cluster2, kmean_cluster2[[y]] == 1) 
InhibPercent = as.data.frame(table(PullData$`k2$cluster`))
InhibPercent$Percent = InhibPercent$Freq/dim(PullData)[1]*100
InhibPercent$Freq = NULL
colnames(InhibPercent) = c("Cluster", "InhibPercent")
CompilePercents = merge(AllPercent, InhibPercent, by = "Cluster", all=T)
CompilePercents$Inhib = y
CompilePercents[is.na(CompilePercents)] = 0
CompilePercents$Delta = CompilePercents$InhibPercent -CompilePercents$AllPercent
if(y == "P"){
DeltaData =  CompilePercents
}else{
DeltaData = rbind(DeltaData, CompilePercents)  
}
}

DeltaData$Cluster = factor(DeltaData$Cluster, levels = c(2, 1))
DeltaData2 = subset(DeltaData, DeltaData$Cluster == 1)
DeltaData2 = DeltaData2[order(DeltaData2$InhibPercent), ]
DeltaData$Inhib = factor(DeltaData$Inhib, levels = DeltaData2$Inhib)
OutputPCA[["Freq"]]  = ggplot(DeltaData, aes(fill=Cluster, y=InhibPercent, x=Inhib)) + 
    geom_bar(position="stack", stat="identity")+coord_flip() + scale_fill_manual(values = c("1" = ColourLinear, "2" = ColourTwoWay))+theme_classic() + scale_y_continuous(expand = c(0,0)) + theme(axis.text = element_text(face = "bold", size = 8), legend.position="top") + ylab("Normalised percent/cluster") + xlab("") 

PCA_Main = ggarrange(plotlist = OutputPCA, ncol = 3, nrow = 1, widths = c(0.8, 1, 0.8))

#


OutputComps = list()
for(dt in c("Morphology", "CellNoNorm_2", "CellNoNorm_4", "CellNoNorm_6", "Prolif_2", "Prolif_4", "Prolif_6", "Apoptosis_2", "Apoptosis_4", "Apoptosis_6", "Rex1", "Oct4", "Dnmt3b", "Fgf5", "Lefty2", "Otx2", "Mixl1", "EB2", "EB3", "EB4" )){
if(dt == "Morphology"){ylabtitle = "Morphology Score"}else if(dt %in% c("CellNoNorm_2", "CellNoNorm_4", "CellNoNorm_6")){ylabtitle = "Fold Change"}else if(dt %in% c("Prolif_2", "Prolif_4", "Prolif_6")){ylabtitle = "% BrdU +"}else if(dt %in% c("Apoptosis_2", "Apoptosis_4", "Apoptosis_6")){ylabtitle = "% Annexin V+"}#else{ylabtitle = expression(Log[2]~fold~change)}

if(dt %in% c("CellNoNorm_2", "CellNoNorm_4", "CellNoNorm_6")){ptitle = gsub("CellNoNorm_", "Cell Number - Day ", dt)}else if(dt %in% c("Prolif_2", "Prolif_4", "Prolif_6")){ptitle = gsub("Prolif_", "Proliferation - Day ", dt)}else if(dt %in% c("Apoptosis_2", "Apoptosis_4", "Apoptosis_6")){ptitle =  gsub("Apoptosis_", "Apoptosis - Day ", dt)}else if(dt %in% c("EB2", "EB3", "EB4")){ptitle =  gsub("EB", "Brachyury - EB", dt)}else{ptitle = dt}

  
PullData = AllVariables4[,c(dt,"k2$cluster")]
colnames(PullData) = c("Value", "KClust")
#PullData$KClust = factor(PullData$KClust, levels = c(1,2))  
Clust1 = subset(PullData, PullData$KClust == 1)
Clust2 = subset(PullData, PullData$KClust == 2)
Tres = t.test(Clust1$Value, Clust2$Value, alternative = "two.sided", var.equal = FALSE)
if(Tres$p.value >= 0.05){
OutputComps[[dt]] = ggboxplot(PullData, x = "KClust", y = "Value", color = ColourTwoWay, title = ptitle, ylab = ylabtitle, xlab = "")
OutputComps[[dt]] = ggpar(OutputComps[[dt]], xlab = F, font.main = c(8,"bold"), font.x = c(8), font.y = c(8), font.tickslab = c(8))
if(dt %in% c("Rex1", "Oct4", "Dnmt3b", "Fgf5", "Lefty2", "Otx2", "Mixl1", "EB2", "EB3", "EB4")){
OutputComps[[dt]] = ggboxplot(PullData, x = "KClust", y = "Value", color = ColourTwoWay, title = ptitle, ylab = "Log2 fold change", xlab = "")
OutputComps[[dt]] = ggpar(OutputComps[[dt]], xlab = F, font.main = c(8,"bold.italic"), font.x = c(8), font.y = c(8), font.tickslab = c(8))
}
}else{
Outs = as.data.frame(t(c(1, 2, Tres$p.value, "*")))
colnames(Outs) = c("group1", "group2", "p", "SigIf")
OutputComps[[dt]] = ggboxplot(PullData, x = "KClust", y = "Value", color = ColourTwoWay, title = ptitle, ylab = ylabtitle, xlab = "") + stat_pvalue_manual(Outs, y.position = max(PullData$Value)*1.1, step.increase = 0.1, label = "SigIf")
OutputComps[[dt]] = ggpar(OutputComps[[dt]], xlab = F, font.main = c(8,"bold"), font.x = c(8), font.y = c(8), font.tickslab = c(8))
if(dt %in% c("Rex1", "Oct4", "Dnmt3b", "Fgf5", "Lefty2", "Otx2", "Mixl1", "EB2", "EB3", "EB4")){
OutputComps[[dt]] = ggboxplot(PullData, x = "KClust", y = "Value", color = ColourTwoWay, title = ptitle, ylab = "Log2 fold change", xlab = "") + stat_pvalue_manual(Outs, y.position = max(PullData$Value)*1.1, step.increase = 0.1, label = "SigIf")
OutputComps[[dt]] = ggpar(OutputComps[[dt]], xlab = F, font.main = c(8,"bold.italic"), font.x = c(8), font.y = c(8), font.tickslab = c(8))
}  
}}
OUTPUT = ggarrange(plotlist = OutputComps, ncol = 5, nrow= 4, align="hv") 
OUTPUT2= ggarrange(PCA_Main, OUTPUT, ncol = 1, nrow= 2, heights = c(0.5, 1), align="hv") 


pdf(paste(FilePath, "FigureSX_PCA.pdf", sep=""), width = 10, height = 12)
print(OUTPUT2)
dev.off()

```


### FIGURE S11: Functional Assay
```{r}
FA_list = list()
Condit = c("1000 U/mL LIF", "330 LIF+Pro+DMSO", "U", "S", "L", "R", "P", "U+S", "U+L", "U+R", "U+P", "S+L", "S+R", "S+P", "L+P", "R+P", "U+S+L", "U+S+R", "U+R+P", "U+S+P","U+L+P", "S+L+P", "S+R+P", "U+S+R+P", "U+S+L+P")
FirstUpreg = as.data.frame(matrix(ncol = 2, nrow = 0))
colnames(FirstUpreg) = c("Condition", "UpregDay")

MaxVal = max(FunctionalAssay$Value) *1.1
MinVal = min(FunctionalAssay$Value)*1.1
FunctionalAssay$Exp = NULL
for(x in Condit){
FA_ForSTATS = subset(FunctionalAssay, FunctionalAssay$Condition == x)

ControlGroup = as.data.frame(matrix(ncol = 0, nrow = max(as.data.frame(table(FA_ForSTATS$Day))$Freq)))  
ControlGroup$Condition = "Baseline"
ControlGroup$Day = "Day 0"
ControlGroup$Value = 0


CombineForDunnetts = rbind(FA_ForSTATS, ControlGroup)    
CombineForDunnetts$Day = factor(CombineForDunnetts$Day, levels = c("Day 0", "EB2", "EB3", "EB4"))

ANOVARes = as.data.frame(DunnettTest(x=CombineForDunnetts$Value, g=CombineForDunnetts$Day)[[1]])
row.names(ANOVARes) = gsub("-Day 0", "", row.names(ANOVARes))

CompileForPlot = FA_ForSTATS %>% group_by(Condition, Day) %>% summarise(n = n(), Mean = mean(Value), stdev = sd(Value), se=sd(Value)/sqrt(n())) 

CompileForPlotWStats = merge(CompileForPlot, ANOVARes, by.x = "Day", by.y = 0)
CompileForPlotWStats$Sig <- ifelse(CompileForPlotWStats$pval <0.05,  "*", NA)


CompileForPlotWStats$DayWn = paste(CompileForPlotWStats$Day, "\n n=", CompileForPlotWStats$n, sep="")
FA_ForSTATSmerge = merge(CompileForPlotWStats, FA_ForSTATS, by = "Day")

CompileForPlotWStats <- CompileForPlotWStats[order(CompileForPlotWStats$Day),] 
CompileForPlotWStats$DayWn = factor(CompileForPlotWStats$DayWn, levels = CompileForPlotWStats$DayWn)


FirstUpregDay = subset(CompileForPlotWStats, CompileForPlotWStats$Sig == "*")
if("EB2" %in% FirstUpregDay$Day){FirstUpregTemp = as.data.frame(t(c(x, "EB2")))
}else if("EB3" %in% FirstUpregDay$Day){FirstUpregTemp = as.data.frame(t(c(x, "EB3")))
}else if("EB4" %in% FirstUpregDay$Day){FirstUpregTemp = as.data.frame(t(c(x, "EB4")))
}else{FirstUpregTemp = as.data.frame(t(c(x, "NA")))}
colnames(FirstUpregTemp) = c("Condition", "UpregDay")
FirstUpreg = rbind(FirstUpreg, FirstUpregTemp)


if(x == "330 LIF+Pro+DMSO"){Title = "330 U/mL LIF \n+ L-pro + DMSO"}else{Title = x}

FA_list[[x]] = ggplot(CompileForPlotWStats, aes(x=DayWn, y=Mean))  + geom_col(fill = ColourTwoWay, color = "#000000")  +theme_classic() + geom_hline(yintercept=0) + ylab("") + xlab("") + geom_errorbar(aes(ymin = Mean-se, ymax = Mean+se), position = position_dodge(width = 0.9), width = 0.2) + theme(axis.text.x = element_text(face = "bold", size = 8), axis.text.y = element_text( size = 8), legend.position="none", plot.title = element_text(face = "bold", size = 8)) + scale_y_continuous(limits = c(MinVal, MaxVal)) + ggtitle(Title) + geom_point( aes(color = ColourTwoWay, shape = Sig, y = Mean + sign(Mean) * (se + (se*3.5))), position = position_dodge(width = 0.9), size = 1, show.legend = F) + scale_shape_manual(values=c(8)) + geom_point(data=FA_ForSTATSmerge, aes(x = DayWn, y =Value), size=0.5)

}      

FunctAssayFig = ggarrange(plotlist = FA_list, ncol =5, nrow=5)

pdf(paste(FilePath, "FigureS7_FunctionalAssay.pdf", sep=""), width = 8, height =  9)
print(FunctAssayFig)
dev.off()



####


FirstUpreg$U = ifelse(grepl("U", FirstUpreg$Condition, fixed = T) & ! FirstUpreg$Condition %in% c("1000 U/mL LIF", "330 LIF+Pro+DMSO") , 1, 0)
FirstUpreg$S = ifelse(grepl("S", FirstUpreg$Condition, fixed = T) & ! FirstUpreg$Condition %in% c("1000 U/mL LIF", "330 LIF+Pro+DMSO"), 1, 0)
FirstUpreg$L = ifelse(grepl("L", FirstUpreg$Condition, fixed = T) & ! FirstUpreg$Condition %in% c("1000 U/mL LIF", "330 LIF+Pro+DMSO"), 1, 0)
FirstUpreg$R = ifelse(grepl("R", FirstUpreg$Condition, fixed = T) & ! FirstUpreg$Condition %in% c("1000 U/mL LIF", "330 LIF+Pro+DMSO"), 1, 0)
FirstUpreg$P = ifelse(grepl("P", FirstUpreg$Condition, fixed = T) & ! FirstUpreg$Condition %in% c("1000 U/mL LIF", "330 LIF+Pro+DMSO"), 1, 0)

AllPercent = as.data.frame(table(FirstUpreg$UpregDay))
AllPercent$Percent = AllPercent$Freq/dim(FirstUpreg)[1]*100
AllPercent$Freq = NULL
colnames(AllPercent) = c("Cluster", "AllPercent")
AllPercent[is.na(AllPercent)] = "NA"

AllPercent$Cluster = factor(AllPercent$Cluster, levels = c("EB2", "EB3", "EB4", "NA"))
FA2 = list()
FA2[["Freq"]]  = ggplot(AllPercent, aes(y=AllPercent, x=Cluster)) +  geom_col(fill = ColourLinear, color = "#000000")+theme_classic() + theme(axis.text.x = element_text(face = "bold", size = 8), axis.text.y = element_text(size = 8), axis.title = element_text(size = 8))+ ylab("Frequency of upregualtion (%)") + xlab("") 


for(y in rev(c("U", "S", "L", "R", "P"))){
PullData = subset(FirstUpreg, FirstUpreg[[y]] == 1) 
InhibPercent = as.data.frame(table(PullData$UpregDay))
InhibPercent$Percent = InhibPercent$Freq/dim(PullData)[1]*100
InhibPercent$Freq = NULL
colnames(InhibPercent) = c("Cluster", "InhibPercent")
CompilePercents = merge(AllPercent, InhibPercent, by = "Cluster", all=T)
CompilePercents$Inhib = y
CompilePercents[is.na(CompilePercents)] = 0
CompilePercents$Delta = CompilePercents$InhibPercent -CompilePercents$AllPercent
if(y == "P"){
DeltaData =  CompilePercents
}else{
DeltaData = rbind(DeltaData, CompilePercents)  
}
}

DeltaData$Inhib = factor(DeltaData$Inhib, levels = c("U", "S", "L", "R", "P"))
FA2[["Delta"]]  = ggplot(DeltaData, aes(y=Delta, x=Cluster)) + facet_wrap(~Inhib, ncol = 5)+  geom_col(fill = ColourFiveWay, color = "#000000")+theme_classic() + theme(axis.text.x = element_text(face = "bold", size = 8), axis.text.y = element_text(size = 8), strip.background = element_blank(), strip.text = element_blank(), axis.title = element_text(size = 8))+ ylab(expression(Delta)) + xlab("") 


FunctAssayFig2 = ggarrange(plotlist = FA2, ncol =2, nrow=1, widths = c(1,4))
FunctAssayFigCompile = ggarrange(FunctAssayFig, FunctAssayFig2, ncol =1, nrow=2, heights = c(5,1))

pdf(paste(FilePath, "FigureS11_FunctionalAssay.pdf", sep=""), width = 8, height =  11)
print(FunctAssayFigCompile)
dev.off()
```

### BRANN Stats for Table 1
```{r}
SW_Res = as.data.frame(matrix(ncol=3, nrow=0))
colnames(SW_Res) = c("Exp", "SWpval", "Rsq")

for(x in unique(BRANN_AvP$Exp)){
Subs = subset(BRANN_AvP, BRANN_AvP$Exp == x)  
BRANN_SW = as.data.frame(x)
colnames(BRANN_SW) = "Exp"
BRANN_SW$SWpval =  shapiro.test(Subs$Predicted)[[2]]
GetLM = lm(Response~Predicted, data = Subs)
BRANN_SW$Rsq = glance(GetLM)[[1]]
SW_Res = rbind(SW_Res, BRANN_SW)
}
```





